### ISSUE TITLE
BFM Model Front file missing

### ISSUE THREAD

**Issue by abasit-AEV** [yerfor/GeneFace#10]
In the install_guide_lrs3.md the file BFM_model_front.mat seems to be missing on the provided URL. Kindly check that and update the link.
Thank you for sharing the awesome work!

**Comment by yerfor** [comment]
Hi, I have updated the new URL in the latest commit. You can down `BFM_model_front.mat` at [this link](https://drive.google.com/drive/folders/1YCxXKJFfo1w01PzayhnxWSZZK5k7spSH?usp=share_link).

**Comment by abasit-AEV** [comment]
Appreciated!
