### ISSUE TITLE
设置lrs3数据集dataloder的num_workers

### ISSUE THREAD

**Issue by st01tyy** [yerfor/GeneFace#102]
您好，我们使用的是您公开的已经过预处理的lrs3数据集。在训练postnet的时候，val dataloader报错share memory不足。由于一些原因，我们暂时无法调整share memory的大小。请问在哪里可以设置相关dataloader的num_workers参数，使其运行在单进程模式下呢？

**Comment by yerfor** [comment]
你好，有两个解决方案：（1）修改`tasks/audio2motion/dataset_utils/lrs3_dataset.py`里的get_dataloader方法，将里面的num_workers=4修改为num_workers=0；这个方法缺点是io开销很大（2）如果内存足够的话，将data/binary/lrs3的数据集文件夹整个cp到/dev/shm上，这样相当于提前将数据集移动到内存上。然后在训练时设置load_db_to_memory=False，这样训练速度不会受影响，缺点是内存占用比较大。

**Comment by st01tyy** [comment]
感谢您的建议。不过我们将share memory设置为32GB后，仍然在训练至6800步左右时遇到了share memory不足的报错。

**Comment by yerfor** [comment]
可能是训练代码有部分内存泄漏；也可能是ds_workers开的太大，你可以尝试设置ds_workers=0
