### ISSUE TITLE
is deep_3drecon must be install in other env with py=3.6 not in one env geneface python=3.9

### ISSUE THREAD

**Issue by foocker** [yerfor/GeneFace#103]
0. good. it's sames all pipelines contained. 
1. there are two env in your install_guide.md. validate the bindings with GeneFace.
2. what's meaning  of conda activate process_lrs3 ?(deep_3drecon/test.py  xx path should add ../../ in the released code.)

**Comment by yerfor** [comment]
Hi, please pull the latest code, in which only one python env named `geneface` is needed.
