### ISSUE TITLE
facetracker error >>> max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete

### ISSUE THREAD

**Issue by hannahgym** [yerfor/GeneFace#104]
Do you have any idea why I got this message at [L54](https://github.com/yerfor/GeneFace/blob/main/data_util/face_tracking/face_tracker.py#L254) when face_tracker is run over my video?

 `To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin

`

**Comment by hannahgym** [comment]
note that the input video contains only one talking face.

**Comment by hannahgym** [comment]
I tried settign bin_size [[here](https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/renderer/mesh/rasterizer.py#L127)] to zero; but, it took forever to run the code. It is very strange to me why for some videos this is happning.

**Comment by yerfor** [comment]
Hi, it's a bug from face_tracker. The code is borrowed from AD-NeRF. I found we could empirically handle this by try with different random seed during training the 3DMM coefficient.

**Comment by hannahgym** [comment]
appreciate your reply.

**Comment by alchemician** [comment]
@yerfor @hannahgym what is a fix for this? any suggestions here? setting bin size to 0 is taking forever

**Comment by owenmao** [comment]
please check this: https://github.com/facebookresearch/pytorch3d/issues/1064
