### ISSUE TITLE
guide about batch information

### ISSUE THREAD

**Issue by hannahgym** [yerfor/GeneFace#106]
per batch frame I can see you have these information:

'cond', 'cond_win', 'cond_wins', 'rays_o', 'rays_d', 'bg_coords', 'pose', 'idx', 'bg_img', 'H', 'W'

these ones * 'bg_coords', 'pose', 'idx', 'bg_img', 'H', 'W'* are obvious to me what do they mean.

   cond: output of posenet

could you please help me with some simple explanation about these other ones?

>> '[cond_win](https://github.com/yerfor/GeneFace/blob/main/inference/nerfs/lm3d_radnerf_infer.py#L84)' , '[cond_wins](https://github.com/yerfor/GeneFace/blob/main/inference/nerfs/lm3d_radnerf_infer.py#L85)', ['rays_o', 'rays_d',](https://github.com/yerfor/GeneFace/blob/90bffaa4e6787e9b3e92a1dc5608ee47947d39e6/tasks/nerfs/lm3d_nerf_torso.py#L75)

```
ds_sample['rays_o'].shape
torch.Size([1, 1048576, 3])
ds_sample['rays_d'].shape
torch.Size([1, 1048576, 3])

# H*W 1048576
```

Thanks.

**Comment by hannahgym** [comment]
rays_o and rays_d become clear to me based on [this](https://github.com/yerfor/GeneFace/blob/90bffaa4e6787e9b3e92a1dc5608ee47947d39e6/modules/radnerfs/utils.py#L356)

**Comment by hannahgym** [comment]
so, the only remaining ones are >> '[cond_win](https://github.com/yerfor/GeneFace/blob/main/inference/nerfs/lm3d_radnerf_infer.py#L84)' , '[cond_wins](https://github.com/yerfor/GeneFace/blob/main/inference/nerfs/lm3d_radnerf_infer.py#L85)',

if you could kindly explain about them, it would be appreciated

**Comment by hannahgym** [comment]
could you plz guide where in the code computation of (7) and (8) is happening?

<img width="756" alt="Screenshot 2023-04-17 at 4 17 09 PM" src="https://user-images.githubusercontent.com/43616693/232630215-c9690bfb-1880-4da4-b72c-9dd849d29102.png">

**Comment by yerfor** [comment]
> so, the only remaining ones are >> '[cond_win](https://github.com/yerfor/GeneFace/blob/main/inference/nerfs/lm3d_radnerf_infer.py#L84)' , '[cond_wins](https://github.com/yerfor/GeneFace/blob/main/inference/nerfs/lm3d_radnerf_infer.py#L85)',
> 
> if you could kindly explain about them, it would be appreciated


cond_win responds to the landmark condition at current frame, which should be [1, 204].
cond_wins denotes the cond_win in adjacent frames, which should be [3, 1, 204]. 
We use cond_wins because we need adjacent information to improve time consistency of the rendered result.

**Comment by yerfor** [comment]
> could you plz guide where in the code computation of (6) (7) and (8) is happening?
> 
> <img alt="Screenshot 2023-04-17 at 4 17 09 PM" width="756" src="https://user-images.githubusercontent.com/43616693/232630215-c9690bfb-1880-4da4-b72c-9dd849d29102.png">

Equation 6,7,8 are mainly about volume rendering. Currently we use the volume rendering code from torch-ngp, the code is located at `modules/radnerfs/raymarching`, which is written in CUDA.
