### ISSUE TITLE
Steps to replicate quantitative results shown in Table 1 of the paper

### ISSUE THREAD

**Issue by nagendervss** [yerfor/GeneFace#107]
Thank you for this work. Would you be able to give the steps to replicate the quantitative results (of GeneFace) shown in Table 1 of the paper?

**Comment by yerfor** [comment]
Hello, for FID, we use [this repo](https://github.com/mseitzer/pytorch-fid), for SyncScore, see [this repo](https://github.com/joonson/syncnet_python), for Error-related metrics, you can see the tensorboard.

**Comment by nagendervss** [comment]
Thank you for your response. Would you be able to give me the names of the videos that you have used for training and inference, both in-domain and out-of-domain? In the link that you have provided for other target person videos, there are 8 videos. In the paper (Section 4, Dataset Preparation), it is mentioned that 5 videos have been utilized for experiments. Which of the 8 videos are the mentioned 5 videos? Which video and audio files did you use for out-of-domain testing? Thank you for your time.
