### ISSUE TITLE
Given input size: (192x2x2). Calculated output size: (192x0x0). Output size is too small

### ISSUE THREAD

**Issue by afan249** [yerfor/GeneFace#108]
您好，在训练lm3d_nerf时，报错，该如何解决呢

**Comment by afan249** [comment]
![image](https://user-images.githubusercontent.com/24600547/232753949-2e084522-591f-44c6-8a91-0c4b945280fd.png)
看着已经执行了20万step了

**Comment by afan249** [comment]
您好，又出现了上面的问题了，请问您上面说的lpips 在哪个位置，该怎么改呢

**Comment by yerfor** [comment]
你好，初步猜测是您的训练数据有几帧有问题，因为lpips是根据mouth位置的boundingbox来渲染对应的patch，然后输入到一个alexnet里计算loss的。所以有可能在你出错的这几帧，对应的mouth rect有问题。

**Comment by afan249** [comment]
您好，我该如何解决这个问题呢，
1.是需要重新录制一个视频吗
2.还是重新跑一下CUDA_VISIBLE_DEVICES=0 data_gen/nerf/process_data.sh $VIDEO_ID 这个脚本
3.我的视频的原格式不满足条件是直接通过 ppmeg命令转过来的转化命令为ffmpeg -i test.mov -r 25 -s 512:512 out.mp4

**Comment by yerfor** [comment]
我觉得可以先定位一下问题，刚才我只是提出了一种可能。你可以再次跑一下原来出问题的训练代码，这次打印一下出错的帧的index，然后看看对应index的视频帧是否真的有问题

**Comment by stevetatum** [comment]
你好，请问你最后是怎么解决这个问题的

**Comment by muximuxi** [comment]
在处理到postnet时候，也发生了同样的报错，请问是怎么解决的，原视频必须都是正面脸，不能有扭头之类的吗？

**Comment by jackyin68** [comment]
How to fix this problem?
