### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/May/aud_esperanto.npy'

### ISSUE THREAD

**Issue by pyh007** [yerfor/GeneFace#109]
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/May/aud_esperanto.npy'  ，Why hasn't it been generated

**Comment by yerfor** [comment]
It means the esperanto extraction has failed. Please check the corresponding step. It is usually caused by hugging face downloading failed.

**Comment by zhangkun07** [comment]
Hello,I meet this problem , how did you solve it,  could you tell me ,thank you very much

**Comment by shisuimengli** [comment]
Has your issue been resolved? I encountered the same problem and couldn't find a solution.
