### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by zhangziliang04** [yerfor/GeneFace#11]
![image](https://user-images.githubusercontent.com/646709/218254840-15a34bb6-4fdc-4abc-b4c3-852862bdf84f.png)

utils导入失败，是不是有文件缺失啊？

**Comment by yerfor** [comment]
Hello, please run `export PYTHONPATH=.` in the GeneFace root directory.

**Comment by zhangziliang04** [comment]
ths, I have find the result. I through sys.path.append('root_path'), have solve it.ths.

**Comment by zhangziliang04** [comment]
close
