### ISSUE TITLE
新训练视频时yaml配置文件的问题

### ISSUE THREAD

**Issue by yuanhei1118** [yerfor/GeneFace#110]
作者们，你们好！
在你们提供的Readme.md文件中，有这么一句话：
> 要训练一个名为 <video_id>.mp4的新视频，你应该把它放在 data/raw/videos/目录下，然后在 egs/datasets/videos/<video_id>目录下创建一个新文件夹，并根据提供的示例文件夹 egs/datasets/videos/May添加对应的yaml配置文件。

最后一句话，怎么理解呢？是照着egs/datasets/videos/May中yaml配置文件，只是将VIDEO_ID改成要训练的视频ID吗？May中所有yaml配置文件全部都要复制一遍到新ID文件夹下吗？
希望得到回复，谢谢。

**Comment by yerfor** [comment]
是的，直接复制May中配置文件修改video_id就可以。目前仅支持mp4格式。另外注意分辨率仅支持512x512.

**Comment by yuanhei1118** [comment]
> 是的，直接复制May中配置文件修改video_id就可以。目前仅支持mp4格式。另外注意分辨率仅支持512x512.

分辨率都不能修改吗？那转换视频格式和分辨率你们用到哪些工具和技术呢？有推荐吗？

**Comment by yerfor** [comment]
我个人是使用Adobe的Premiere来截取出512x512的视频。修改视频格式的话推荐使用ffmpeg。

**Comment by yerfor** [comment]
不好意思，暂时没有修改这个的计划，不过应该比较方便。你可以修改一下含有512的代码，改为你想要的数值

**Comment by yuanhei1118** [comment]
> 不好意思，暂时没有修改这个的计划，不过应该比较方便。你可以修改一下含有512的代码，改为你想要的数值

原视频有2k或1080p，裁取的话是只留头部，那可能手势就放不进去了，没关系吗？
还有25G左右的lrs3数据集解压后，在后续哪个步骤用到这些解压文件了呢？

**Comment by yuanhei1118** [comment]
> 不好意思，暂时没有修改这个的计划，不过应该比较方便。你可以修改一下含有512的代码，改为你想要的数值

你们这个代码都是定好了512的吗？分辨率小点只是为了加速训练？有设置传参的入口吗还是说一个一个改？

**Comment by yuanhei1118** [comment]
> 不好意思，暂时没有修改这个的计划，不过应该比较方便。你可以修改一下含有512的代码，改为你想要的数值

你们这个代码都是定好了512的吗？分辨率小点只是为了加速训练？有设置传参的入口吗还是说一个一个改？

**Comment by yerfor** [comment]
所有May都要修改的

**Comment by yerfor** [comment]
> > 不好意思，暂时没有修改这个的计划，不过应该比较方便。你可以修改一下含有512的代码，改为你想要的数值
> 
> 你们这个代码都是定好了512的吗？分辨率小点只是为了加速训练？有设置传参的入口吗还是说一个一个改？

对，定好了512。理论上大一点也能训练。没有设置传参入口

**Comment by yuanhei1118** [comment]
> 所有May都要修改的

感觉这个May在很多文件中都有，要么是VIDEO_ID要么是路径名
除了May, 你们还训练了多少个新视频？ 都是这么处理的吗？
你们最新的release1.1.0版本中的文件都是在训练May之后的文件吗？

**Comment by yerfor** [comment]
论文里的实验前后测试了10个视频，存在主页readme里提供的谷歌网盘了。都是同一个pipeline。

1.1.0版本里的文件是lrs3数据集和May视频训练的模型。其中audio2motion和syncnet可以通用。其他利用了May数据训练的模型需要在自己的视频上重新训练。

**Comment by yuanhei1118** [comment]
> 论文里的实验前后测试了10个视频，存在主页readme里提供的谷歌网盘了。都是同一个pipeline。
> 
> 1.1.0版本里的文件是lrs3数据集和May视频训练的模型。其中audio2motion和syncnet可以通用。其他利用了May数据训练的模型需要在自己的视频上重新训练。

audio2motion和syncnet这两个步骤我都没跑，postnet跑了一晚上，只有20000steps，我看文件里都写得40000steps，怎么回事？
我跑通了你们那个提供的这个1.1.0版本，最后出来的是10秒的男声合成的May视频，这个男声哪里来的？
“所有May都要修改的”需要修改为新视频ID的值不少吧...一个文件一个文件翻开找到并修改的吗？

**Comment by yerfor** [comment]
1. 你可以看看调用的事哪个config文件，这个是有继承关系的
2. data/raw/val_wavs/zozo.wav
3. 同1，实际操作的时候你可以在video的文件夹写个base.yaml，从里面继承一些video-specific的信息，比如video_id

**Comment by yuanhei1118** [comment]
> 1. 你可以看看调用的事哪个config文件，这个是有继承关系的
> 2. data/raw/val_wavs/zozo.wav
> 3. 同1，实际操作的时候你可以在video的文件夹写个base.yaml，从里面继承一些video-specific的信息，比如video_id

你们都是跑满4万个steps吗？
这个音频文件也是要自己制作的是吗？你们试过中文的音频没？
感觉你说的第3点，我没理解，你是在回答我上个comment的最后一个问题吗？你能补充一下吗？

**Comment by yuanhei1118** [comment]
> 1. 你可以看看调用的事哪个config文件，这个是有继承关系的
> 2. data/raw/val_wavs/zozo.wav
> 3. 同1，实际操作的时候你可以在video的文件夹写个base.yaml，从里面继承一些video-specific的信息，比如video_id

音频文件有格式要求吗？都需要wav格式吗？

**Comment by yerfor** [comment]
> > 1. 你可以看看调用的事哪个config文件，这个是有继承关系的
> > 2. data/raw/val_wavs/zozo.wav
> > 3. 同1，实际操作的时候你可以在video的文件夹写个base.yaml，从里面继承一些video-specific的信息，比如video_id
> 
> 你们都是跑满4万个steps吗？ 这个音频文件也是要自己制作的是吗？你们试过中文的音频没？ 感觉你说的第3点，我没理解，你是在回答我上个comment的最后一个问题吗？你能补充一下吗？

1. 跑满4w steps，然后根据曲线图，一般会选择早期的ckpt，具体你可以看一下我在train_models.md里面写的tips。
2. 是的，我们试过用中文歌声合成算法来合成歌声，具体可以看下project page里面提供的demo
3. “所有May都要修改的”需要修改为新视频ID的值不少吧...一个文件一个文件翻开找到并修改的吗。是的，你可以这么做，这个可以根据自己工程的方便来做些调整，并不涉及算法本身。

**Comment by yerfor** [comment]
> > 1. 你可以看看调用的事哪个config文件，这个是有继承关系的
> > 2. data/raw/val_wavs/zozo.wav
> > 3. 同1，实际操作的时候你可以在video的文件夹写个base.yaml，从里面继承一些video-specific的信息，比如video_id
> 
> 音频文件有格式要求吗？都需要wav格式吗？

你可以看下inference模块里面的save_wav16k函数，他会利用ffmpeg，将mp3、wav、mp4、avi等格式的音视频里面的音频转换成我们需要的16k wav文件。不需要修改代码。

def save_wav16k(self, inp):
        source_name = inp['audio_source_name']
        supported_types = ('.wav', '.mp3', '.mp4', '.avi')
        assert source_name.endswith(supported_types), f"Now we only support {','.join(supported_types)} as audio source!"
        wav16k_name = source_name[:-4] + '_16k.wav'
        self.wav16k_name = wav16k_name
        extract_wav_cmd = f"ffmpeg -i {source_name} -f wav -ar 16000 {wav16k_name} -y"
        os.system(extract_wav_cmd)
        print(f"I have extracted wav file (16khz) from {source_name} to {wav16k_name}.")

**Comment by yuanhei1118** [comment]
> > > 1. 你可以看看调用的事哪个config文件，这个是有继承关系的
> > > 2. data/raw/val_wavs/zozo.wav
> > > 3. 同1，实际操作的时候你可以在video的文件夹写个base.yaml，从里面继承一些video-specific的信息，比如video_id
> > 
> > 
> > 你们都是跑满4万个steps吗？ 这个音频文件也是要自己制作的是吗？你们试过中文的音频没？ 感觉你说的第3点，我没理解，你是在回答我上个comment的最后一个问题吗？你能补充一下吗？
> 
> 1. 跑满4w steps，然后根据曲线图，一般会选择早期的ckpt，具体你可以看一下我在train_models.md里面写的tips。
> 2. 是的，我们试过用中文歌声合成算法来合成歌声，具体可以看下project page里面提供的demo
> 3. “所有May都要修改的”需要修改为新视频ID的值不少吧...一个文件一个文件翻开找到并修改的吗。是的，你可以这么做，这个可以根据自己工程的方便来做些调整，并不涉及算法本身。

曲线图是利用什么作的图？tips和中文歌曲demo我都有看过
虽然不设计算法本身，但是你们是作者，知道文件里写的这个May有很多而且不好找, 这样就很难新建视频去复现实验了呀

**Comment by yerfor** [comment]
曲线图是tensorboard里的图。

你只需要修改egs/datasets/videos/May内配置文件的video_id即可，以及lm3d_radnerf_torso.yaml的head_model_dir。我觉得并不是很难修改。

**Comment by yuanhei1118** [comment]
> 曲线图是tensorboard里的图。
> 
> 你只需要修改egs/datasets/videos/May内配置文件的video_id即可，以及lm3d_radnerf_torso.yaml的head_model_dir。我觉得并不是很难修改。

我记得tensorboard需要日志文件目录即logdir，这个在GeneFace项目的哪个路径位置呢？
好的，很感谢您的耐心解答

**Comment by yerfor** [comment]
这个logdir存在`checkpoints/<exp_name>/logs`中

**Comment by yerfor** [comment]
> > 曲线图是tensorboard里的图。
> > 你只需要修改egs/datasets/videos/May内配置文件的video_id即可，以及lm3d_radnerf_torso.yaml的head_model_dir。我觉得并不是很难修改。
> 
> egs/datasets/videos/May的配置文件有一些文件中也有这个head_model_dir，只需要改lm3d_radnerf_torso.yaml文件中的吗？ 我看到`head_model_dir: checkpoints/May/lm3d_radnerf`这个文件夹是从 `May.zip`解压来的，是你们提供的，不是代码生成的，这个May换了其他ID的路径名就没有没有这个lm3d_radnerf这个目录路径的

这个head model就是用lm3d_radnerf.yaml 训练的。提供的May.zip里面的模型都是可以自行训练的。
