### ISSUE TITLE
tensorboards of step 1 and step 2

### ISSUE THREAD

**Issue by hannahgym** [yerfor/GeneFace#111]
could you plz share screenshots of the tensorboards for 
Step1. Train the SyncNet Model
Step2. Train the Audio2motion model

over lrs3?

thanks.

**Comment by yerfor** [comment]
Here you are. This audio2motion:

![image](https://user-images.githubusercontent.com/48365204/233265448-4cdaf146-c8a9-4466-9904-d558cb21cbbf.png)

![image](https://user-images.githubusercontent.com/48365204/233265483-6f056878-d17e-48c5-9b6a-fa9fac6878a1.png)

**Comment by yerfor** [comment]
This is postnet for May.mp4

![image](https://user-images.githubusercontent.com/48365204/233265683-69f031c8-801e-45d0-b761-880a0ee79714.png)

![image](https://user-images.githubusercontent.com/48365204/233265700-13adddfd-54be-4c33-809d-ec24fa3bda13.png)

![image](https://user-images.githubusercontent.com/48365204/233265729-8b051f5c-c6b1-43cf-bd3a-cd55779717fb.png)

**Comment by yerfor** [comment]
This is syncnet:

![image](https://user-images.githubusercontent.com/48365204/233265854-3d135447-82e0-4c8a-95bb-47c3759f07e0.png)
