### ISSUE TITLE
对视频有什么要求

### ISSUE THREAD

**Issue by afan249** [yerfor/GeneFace#113]
请问i一下，对需要训练的视频有什么要求呢，除了fps=25，512*512， 时长大概3-5min外，说话人说话的快慢，离摄像头的远近等有没有要求，还有就是一般的视频训练时，用May的相关参数直接就可以达到正常的效果，还是不同的视频还需要调整不同的配置

**Comment by yerfor** [comment]
你好，除了fps=25，512*512，还需要躯干没有较大幅度的运动（比如转90度），其他没有要求。时长大于3分钟，多多益善。
