### ISSUE TITLE
没有找到生成的视频

### ISSUE THREAD

**Issue by silence-tang** [yerfor/GeneFace#116]
作者您好，感谢您的开源工作！
有一个问题想请教一下：
我在执行`bash scripts/infer_lm3d_radnerf.sh`后，命令行输出"The synthesized video is saved at infer_out/May/pred_video/zozo_radnerf_torso_smo.mp4"，但是无法在该路径找到这个mp4视频，只有“GeneFace/infer_out/May/pred_video/tmp_imgs/zozo_radnerf_torso_smo”这个路径下是推理出的272个视频帧，请问如何解决？
诚盼回复，谢谢！

**Comment by yerfor** [comment]
你好，能够生成视频帧的话应该GeneFace的主要工作已经顺利完成了。剩下的步骤是利用ffmpeg将连续视频帧整合音频形成最终的视频。我猜测是因为ffmpeg出错。一个常见的可能是我们使用的x264编码器没有被顺利安装。你可以试试`conda install ffmpeg`，这样安装的ffmpeg会自动一起安装x264编码器。

**Comment by silence-tang** [comment]
您好，是这个问题。我刚才把ffmpeg的-v quiet去掉发现提示`ffmpeg Unknown encoder 'libx264'`，应该是x264编码器没被安装，我正准备重新conda install ffmpeg，谢谢！

**Comment by tito-dt** [comment]
感谢，我也是这个问题，通过conda install ffmpeg 解决了！
