### ISSUE TITLE
缺少mat文件

### ISSUE THREAD

**Issue by WenLinLliu** [yerfor/GeneFace#119]
下载checkpoint进行推理
推理时报错没有文件BFM_model_front.mat

**Comment by yerfor** [comment]
![image](https://user-images.githubusercontent.com/48365204/233962214-25e377d5-8c3b-45ac-b470-5b691f3ab673.png)

你好，你可以通过`docs/prepare_env/install_guide-zh.md`中的3.3步进行下载
