### ISSUE TITLE
"data/raw/val_wavs/zozo_16k_deepspeech.npy" not found

### ISSUE THREAD

**Issue by zimonitrome** [yerfor/GeneFace#12]
Hello I'm stuck at step 4 of the quick start:

```
bash scripts/infer_postnet.sh
bash scripts/infer_lm3d_nerf.sh
```

Running `scripts/infer_lm3d_nerf.sh` asks for `data/raw/val_wavs/zozo_16k_deepspeech.npy` but that file was never generated in any previous step. Am I missing something?

**Comment by yerfor** [comment]
Hi, the bug may locate at  `line75` in `inference/nerfs/lm3d_nerf_infer.py`, which uses my absolute GeneFace python interpreter to generate the deepspeech feature of `zozo.wav` and saved it into `data/raw/val_wavs/zozo_16k_deepspeech.npy`. 

I have changed the path in the latest commit. Hopefully, it will solve this issue.

**Comment by zimonitrome** [comment]
Thanks! That was indeed the issue.
