### ISSUE TITLE
训练Audio2Motion模型时报错

### ISSUE THREAD

**Issue by buaajky** [yerfor/GeneFace#120]
您好！
训练Audio2Motion模型时，执行`CUDA_VISIBLE_DEVICES=0 python tasks/run.py --config=egs/datasets/videos/lrs3/lm3d_vae_sync.yaml --exp_name=lrs3/lm3d_vae_sync`报错如下：
```
| Unknow hparams:  []
Traceback (most recent call last):
  File "/root/autodl-tmp/GeneFace/tasks/run.py", line 18, in <module>
    set_hparams()
  File "/root/autodl-tmp/GeneFace/utils/commons/hparams.py", line 46, in set_hparams
    assert os.path.exists(args.config)
AssertionError
```
步骤1. 训练SyncNet模型可以正常运行。
请问可能是哪里的问题？谢谢

**Comment by yerfor** [comment]
你好，看起来是因为config变量对应的yaml文件不存在。或许你可以检查一下文件名称和路径。

**Comment by yerfor** [comment]
你好，不能。因为你提取的是2d landmark，不具备深度信息，并且pose相关。而我们采用的3d landmark是从3dmm mesh里面重构的，首先具有深度信息，其次pose无关。

在我们早期的工作也尝试过直接使用2d landmark，结论是性能会明显减弱。
