### ISSUE TITLE
训练出来的视频 发现 背景与头部粘在了一起 

### ISSUE THREAD

**Issue by afan249** [yerfor/GeneFace#122]

**Comment by afan249** [comment]
https://user-images.githubusercontent.com/24600547/234195730-d3188da0-6eda-47d6-83d9-dca22f32f1f2.mp4

**Comment by afan249** [comment]
您好，后面的背景红色一直在跟着动，该如何解决这个问题呢

**Comment by yerfor** [comment]
你好，可能是因为数据预处理的时候，face parsing的预训练模型识别错误。你可以换一个视频试试。
