### ISSUE TITLE
项目会继续解决头像晃动的问题吗

### ISSUE THREAD

**Issue by web3aivc** [yerfor/GeneFace#125]
感谢你们提供相对完整的方案。请问下你们使用TH1KH训练的模型会重新公布么？有没有使用新的3DMM提取器，头像晃动的问题有没有解决？

_Originally posted by @yerfor in https://github.com/yerfor/GeneFace/issues/101#issuecomment-1519544589_

**Comment by yerfor** [comment]
会的，可能会在几个月内慢慢改进。
