### ISSUE TITLE
Re open issues 112  process_data.sh  ==> No such file or directory transforms_train.json

### ISSUE THREAD

**Issue by tommysnu** [yerfor/GeneFace#128]
https://github.com/yerfor/GeneFace/issues/112
During running the process_data.sh I get the error.
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/May/transforms_train.json'
Can you help me fix this bug?

**Comment by tommysnu** [comment]
I fixed the problem.

**Comment by jessicawu11** [comment]
> I fixed the problem.

how did you fix the problem？

**Comment by huozhong-in** [comment]
> I fixed the problem.

Please, How to fix it?

**Comment by JoshonSmith** [comment]
> I fixed the problem.
hi~
how did you fix the problem?
