### ISSUE TITLE
无法有效训练RAD-NeRF

### ISSUE THREAD

**Issue by Awj2021** [yerfor/GeneFace#136]
hi, 我在从头训练RAD-NeRF的时候，发现还没有开始就结束了，lrs3数据集也按照要求准备好了，显示的过程如下：

2023-05-19 22:19:04.295508: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-19 22:19:04.859467: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
| cond_prenet Trainable Parameters: 0.050M
| cond_att_net Trainable Parameters: 0.004M
| position_embedder Trainable Parameters: 1.807M
| ambient_net Trainable Parameters: 0.029M
| ambient_embedder Trainable Parameters: 1.111M
| sigma_net Trainable Parameters: 0.041M
| direction_embedder Trainable Parameters: 0.000M
| color_net Trainable Parameters: 0.019M
Sanity Val: 100%|███████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.54step/s]
| Validation results@250000: {'total_loss': 0.0671, 'mse_loss': 0.0014, 'lpips_loss': 0.0656}
250000step [00:00, ?step/s, ambient_loss=7.69e-5, head_psnr=28.5, lr_0=5e-5, mse_loss=0.00142, weights_entropy_loss=0.0292]| Training end..
250000step [00:00, ?step/s, ambient_loss=7.69e-5, head_psnr=28.5, lr_0=5e-5, mse_loss=0.00142, weights_entropy_loss=0.0292]
Epoch 45 ended. Steps: 250001. {'total_loss': 0.0014273179695010185, 'mse_loss': 0.0014167064800858498, 'weights_entropy_loss': 0.02924138866364956, 'ambient_loss': 7.687370816711336e-05, 'head_psnr': 28.487201690673828}

是我哪一步没有设置好吗？谢谢

**Comment by yerfor** [comment]
你好，可能是你训练radnerf的命令行中，--exp_name指向了已经训练好的文件夹
