### ISSUE TITLE
Questions about the "_deepspeech", and "bash scripts/infer_lm3d_nerf.sh"

### ISSUE THREAD

**Issue by NoHateAnymore** [yerfor/GeneFace#14]
Thx for your CONTRIBUTION!!!!

I have some problems about _deepspeech files:

1. What is the difference between "zozo_16k_deepspeech.npy" and "zozo.npy" besides sampling rate.
2. I didn't got "data/raw/val_wavs/zozo_16k_deepspeech.npy" by previous step, which is needed in "bash scripts/infer_lm3d_nerf.sh" step according README.

**Comment by yerfor** [comment]
Hello, 
1. `zozo_16k_deepspeech.npy` is the auto-generated deepspeech file by the inference script.
2.  please pull the latest commit, in which I have fixed this issue. You can refer to [this closed issue](https://github.com/yerfor/GeneFace/issues/12) for more details.
