### ISSUE TITLE
DDP ERROR in "GeneFace/inference/nerfs/base_nerf_infer.py"

### ISSUE THREAD

**Issue by NoHateAnymore** [yerfor/GeneFace#15]
Thx for your CONTRIBUTION!! In base_nerf_infer.py:

def forward_system(self, batches):
        if self.use_ddp:
            del self.dataset
            torch.multiprocessing.set_sharing_strategy('file_system')
            batches = copy.deepcopy(batches)
            mp.spawn(self._forward_nerf_task_ddp, nprocs=self.num_gpus, args=[batches, copy.deepcopy(hparams)])
        else:
            self.nerf_task = self.build_nerf_task()
            self.nerf_task.eval()
            self.nerf_task.to(self.device)
            img_dir = self._forward_nerf_task_single_process(batches)
        return img_dir

if self.use_ddp==True would lead to an UnboundLocalError: local variable 'img_dir' referenced before assignment.

**Comment by yerfor** [comment]
Hi, I have fixed this bug in the latest commit by adding this `img_dir = self.inp['tmp_imgs_dir']`

**Comment by NoHateAnymore** [comment]
> Hi, I have fixed this bug in the latest commit by adding this `img_dir = self.inp['tmp_imgs_dir']`

Cool!
