### ISSUE TITLE
训练完之后没有lm3d_postnet_sync文件夹

### ISSUE THREAD

**Issue by paladinlp** [yerfor/GeneFace#151]
按照教程，我训练了一个全新的人物(我直接用一个新的视频，取名May,覆盖了原有的视频)，训练新的人物完成之后，文件夹的路径应该是：
checkpoints\ May的下面，应该是
             lm3d_postnet_sync
             lm3d_radnerf
            lm3d_radnerf_torso

                
 但是我生成之后，没有May下面的lm3d_postnet_sync文件夹，只有一个postnet文件夹，是不是可能代码哪里修改了配置，导致目的路径不一样了？按理说我修改下bash scripts/infer_postnet.sh的路径应该就可以了，但是合成出来的视频不成功，是不是哪里还有与之相关联的配置？

**Comment by ZhijunLStudio** [comment]
我也存在这个问题

**Comment by yerfor** [comment]
您好，可以将postnet文件夹重命名为lm3d_postnet_sync，然后进入该文件夹中，将config.yaml里面的work_dir的值修改为该文件夹的相对路径名（一般是checkpoints/May/lm3d_postnet_sync）。

很抱歉我最近忙于其他的项目无法及时回复。我们计划在8月份时在本仓库发布GeneFace++的代码，届时最近出现的一些bug我们也会一起解决。
