### ISSUE TITLE
很不错的项目，不要停更啊~~~期待~

### ISSUE THREAD

**Issue by MoroseYu** [yerfor/GeneFace#153]
感谢出色的工作，很不错的项目，就是不要停更啊~~~

**Comment by yerfor** [comment]
Hi，感谢关注，我们会在8月份放出GeneFace++的代码～

**Comment by MoroseYu** [comment]
> 

I've been waiting for a long time, and August is coming soon~ It would be great if the problem of head shaking could be solved. Looking forward to it.
