### ISSUE TITLE
救救！请问utils.common到底是什么库啊

### ISSUE THREAD

**Issue by feifeitu1** [yerfor/GeneFace#155]
一直出现这个报错ModuleNotFoundError: No module named 'utils.commons'，但是明明都安装了utils库，是安装的版本不对吗

**Comment by yerfor** [comment]
你好，utils.commons 位于GeneFace代码的`utils/commons`文件夹。你只需要在geneface的root路径，执行以下语句`export PYTHONPATH=./`，就可以正常import 它了

**Comment by feifeitu1** [comment]
好的谢谢了，之前没看到这个文件
