### ISSUE TITLE
About Postprocessing.

### ISSUE THREAD

**Issue by Lucas-1127** [yerfor/GeneFace#17]
Thank you for open source~

I have seen in https://geneface.github.io/ that your code have postprocess step, which can make results more stable. But I find that my results are not as stable as your final results. Is this inference code including postprocess?

**Comment by yerfor** [comment]
Hi, in the demo video, the 3D landmark is post-processed with an additional carefully hand-crafted process. The automatic post-processing strategy in the current inference code (line 93 in lm3d_nerf_infer.py) is naive and we plan to devise a more generic one in the future.

**Comment by Alpacolypse** [comment]
Would love to know if there is a roadmap for an update on the post processing strategy :)
