### ISSUE TITLE
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

### ISSUE THREAD

**Issue by zydp** [yerfor/GeneFace#170]
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /cpierse/wav2vec2-large-xlsr-53-esperanto/resolve/main/preprocessor_config.json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))"), '(Request ID: 7eba50a5-256c-4d7c-af3d-4a3f48e4e26f)')
---
hi , what can i do to resolve the problem? please help me, thanks.

**Comment by ymwang-2020** [comment]
> ## requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /cpierse/wav2vec2-large-xlsr-53-esperanto/resolve/main/preprocessor_config.json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))"), '(Request ID: 7eba50a5-256c-4d7c-af3d-4a3f48e4e26f)')
> hi , what can i do to resolve the problem? please help me, thanks.
I also encountered the same problem. How did you resolve it？Thanks
