### ISSUE TITLE
GeneFace++ Real-time Inference

### ISSUE THREAD

**Issue by bitnom** [yerfor/GeneFace#175]
When are you planning to release the [GeneFace++](https://genefaceplusplus.github.io) model? I'm really excited to finally be able to do real-time generation for live interaction with LLMs.

**Comment by foocker** [comment]
> When are you planning to release the [GeneFace++](https://genefaceplusplus.github.io) model? I'm really excited to finally be able to do real-time generation for live interaction with LLMs.

here real-time is 30+fps?

**Comment by mrhanCH** [comment]
+1

**Comment by DogeFlow** [comment]
+1

**Comment by KelvinCheng5507** [comment]
+1

**Comment by yerfor** [comment]
Hi, maybe in Feb 2024

**Comment by karelnagel** [comment]
Can't wait!

**Comment by anwoflow** [comment]
Just for clarification, the real time performance will be for generating a video, of a previously 'trained' identity. What is the current performance in terms of training a novel identity?

**Comment by yyheart** [comment]
now 2024年2月

**Comment by yerfor** [comment]
hi, we have released the code at ([https://github.com/yerfor/GeneFacePlusPlus](https://github.com/yerfor/GeneFacePlusPlus)). thanks for your patience.
