### ISSUE TITLE
训练得到了14个 ckpt_steps，怎么看该用哪个 ckpt_steps呀，请问看哪个维度呀？

### ISSUE THREAD

**Issue by tailangjun** [yerfor/GeneFace#193]
我用tensorboard把日志导入，生成了这样几张图
<img width="1660" alt="image" src="https://github.com/yerfor/GeneFace/assets/12316965/eba6063c-a7f6-43d7-8630-76f64b222afe">
<img width="1639" alt="image" src="https://github.com/yerfor/GeneFace/assets/12316965/fc5b5c78-61ec-446f-89c8-7f9169160fb5">
<img width="1655" alt="image" src="https://github.com/yerfor/GeneFace/assets/12316965/1950e05f-8f14-4c6a-9d66-77841dca2fc5">

**Comment by premkumarvl** [comment]
How did you do that? Even I have the ckpts, but I don't know how to view graph results like this. Can you help me in this?

**Comment by tailangjun** [comment]
又读了一遍 train_models-zh.md，发现了这段话
val/mse和 val/sync较小，并且 tr/disc_neg_conf和 tr/disc_pos_conf都约等于0.5（这意味着discriminator已经无法区分正样本和postnet产生的负样本之间的差异）

于是我选择8k步的checkpoint

**Comment by zqdsdfg** [comment]
请问你怎么导入的呀？
