### ISSUE TITLE
无法下载 facebook/hubert-large-ls960-ft

### ISSUE THREAD

**Issue by tailangjun** [yerfor/GeneFace#199]
不知道是什么问题，我的服务器上无法下载 facebook/hubert-large-ls960-ft，推理时一直提示如下错误
Max retries exceeded with url: /facebook/hubert-large-ls960-ft/resolve/main/preprocessor_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f00100c6220>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 42eb3924-f231-4a47-adb4-045cbe62c217)')' thrown while requesting HEAD https://huggingface.co/facebook/hubert-large-ls960-ft/resolve/main/preprocessor_config.json

我本地 mac上使用浏览器可以正常访问 https://huggingface.co/facebook/hubert-large-ls960-ft/，我觉得我应该可以手动把 hubert-large-ls960-ft下下来，然后传到服务器的指定目录，但是我不知道该传到哪个目录下。我尝试过工程根目录和 data_gen/process_lrs3/，发现都不解决问题，有哪位大佬清楚，麻烦解答一下哈。

触发下载 facebook/hubert-large-ls960-ft的代码是这个
$ grep -rn hubert-large-ls960-ft
data_gen/process_lrs3/process_audio_hubert.py:7:wav2vec2_processor = Wav2Vec2Processor.from_pretrained("facebook/hubert-large-ls960-ft")
data_gen/process_lrs3/process_audio_hubert.py:9:hubert_model = HubertModel.from_pretrained("facebook/hubert-large-ls960-ft")

**Comment by tailangjun** [comment]
搞清楚了，下载到本地后，直接传入路径即可
Wav2Vec2Processor.from_pretrained("./hubert-large-ls960-ft")
hubert_model = HubertModel.from_pretrained("./hubert-large-ls960-ft")

**Comment by feifeitu1** [comment]
你好，我也遇到了这个问题，请问是把这两句代码添加到extract_hubert_mel_f0.py文件里吗？

**Comment by feifeitu1** [comment]
你好，我也遇到了这个问题，请问你是下载了哪一个文件啊，我怎么没找到。

**Comment by tailangjun** [comment]
> 你好，我也遇到了这个问题，请问你是下载了哪一个文件啊，我怎么没找到。

在浏览器上打开 https://huggingface.co/facebook/hubert-large-ls960-ft/，下载这些文件即可
config.json  preprocessor_config.json  pytorch_model.bin  tokenizer_config.json  vocab.json

**Comment by feifeitu1** [comment]
好的，非常感谢~

**Comment by gt2ming** [comment]
<img width="493" alt="image" src="https://github.com/yerfor/GeneFace/assets/26201976/5104fbd3-4c5f-4428-9ea5-856a7b3832b3">
一直提示503，无法访问，您那边有下载地址可以帮忙提供一下吗？
