### ISSUE TITLE
本地编译mesh renderer 错误？

### ISSUE THREAD

**Issue by dourcer** [yerfor/GeneFace#2]
十分感谢开源，非常不错的工作。我是在docker内准备环境的，执行
curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg   报超时错误，大概需要vpn，我本地保存bazel-release.pub.gpg然后执行
cat  bazel-release.pub.gpg | gpg --dearmor > bazel.gpg  接着执行后续步骤到 bazel build //kernels:rasterize_triangles_kernel
然后报错：
![image](https://user-images.githubusercontent.com/35617526/216920659-27a44e07-4849-4611-a6d4-542da2400129.png)
目前不知道什么原因？

**Comment by yerfor** [comment]
Hello. Thank you for recognizing this project!
Unfortunately I have not encountered with this error. But based on the log printed below, I guess the reason might be that CUDA hasn't been found. Maybe you could check that whether CUDA is installed correctly？

**Comment by yerfor** [comment]
By the way, for the convenience of other people who might also have trouble installing the mesh renderer, I'd like to share two errors and the corresponding solutions that I encountered during the installation process.

**Error 1** : `tensorflow_framework not found`
**Solution 1** : Go to `lib/python3.7/site-package/tensorflow` in your python environment folder, then create a soft link from `tensorflow_framework.so.x` to `tensorflow_framework.so` via the command `ln -s libtensorflow_framework.so.1 libtensorflow_framework.so`

**Error2** : I got compilation error when install mesh renderer on RTX3090Ti
**Solution2** : add the configuration flag `-D_GLIBCXX_USE_CXX11_ABI=0` in the line 29 of `deep_3drecon/mesh_renderer/kernels/BUILD`. It works for me.

**Comment by hylq66** [comment]
> @dourcer 

Hello, did you fix the above bug
