### ISSUE TITLE
No such file or directory: 'data/processed/videos/May/track_params.pt'

### ISSUE THREAD

**Issue by stevetatum** [yerfor/GeneFace#208]
在执行process_target_person_video-zh.md时，出现错误FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/May/track_params.pt'

FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/May/vid_coeff.npy'
并没有找到对应的文件，请问大家如何解决

**Comment by tailangjun** [comment]
data_gen/nerf/process_data.sh
- 其中第 9步 python data_gen/nerf/extract_3dmm.py --video_id=$VIDEO_ID会生成 vid_coeff.npy
你单独执行一下第 9步，看一下错误信息就知道了

**Comment by stevetatum** [comment]
> data_gen/nerf/process_data.sh
> 
> * 其中第 9步 python data_gen/nerf/extract_3dmm.py --video_id=$VIDEO_ID会生成 vid_coeff.npy
> 
> 你单独执行一下第 9步，看一下错误信息就知道了

/好的，谢谢你，我已经解决了。刚开始执行CUDA_VISIBLE_DEVICES=0 data_gen/nerf/process_data.sh $VIDEO_ID有很多报错，后来针对某些错误上网寻找解决方案，也没有解决了多少，然后今天上午跑的时候莫名其妙就通过了
