### ISSUE TITLE
执行bash scripts/infer_lm3d_radnerf.sh后找不到生成的视频

### ISSUE THREAD

**Issue by stevetatum** [yerfor/GeneFace#209]
执行bash scripts/infer_lm3d_radnerf.sh，命令行显示如图，但是在对应路径上找不到zozo_radnerf_torso_smo.mp4，只有一个同名的文件夹，里面应该是视频对应的
![Snipaste_2023-10-04_18-41-40](https://github.com/yerfor/GeneFace/assets/105970306/e8bd9a2a-bf06-49a8-ba79-b16393078178)
图片

**Comment by stevetatum** [comment]
ffmpeg也是安装好的，libx264也是最新的，但是仍然没有视频

**Comment by stevetatum** [comment]
conda uninstall ffmpeg后重新安装就可以了

**Comment by feifeitu1** [comment]
你好，我也遇到了这个问题，请问你conda uninstall ffmpeg后是直接再conda install ffmpeg吗，为什么我卸载之后就重装不了了？

**Comment by stevetatum** [comment]
> 你好，我也遇到了这个问题，请问你conda uninstall ffmpeg后是直接再conda install ffmpeg吗，为什么我卸载之后就重装不了了？

抱歉，我也不太清楚，我卸载之后重新conda install ffmpeg就好了
