### ISSUE TITLE
合成结果

### ISSUE THREAD

**Issue by Free-D** [yerfor/GeneFace#21]
对于合成视频的唇形和声音的匹配效果很不错，但是感觉多了一些多余的动作，参考[这个链接](https://code-1252138799.cos.ap-beijing.myqcloud.com/zozo.mp4)，请问应该怎么调节才会让视频看上去自然一些

**Comment by yerfor** [comment]
Hi, maybe you could hand-craft the 3D landmark sequence, e.g., you could set the landmark of eye part to a fixed value. We are currently working on a more elegant postprocessing strategy to automatically handle this unstable problem, please stay tuned!
