### ISSUE TITLE
RuntimeError: Given input size: (192x2x2). Calculated output size: (192x0x0). Output size is too small

### ISSUE THREAD

**Issue by stevetatum** [yerfor/GeneFace#212]
进行CUDA_VISIBLE_DEVICES=0 python tasks/run.py --config=egs/datasets/videos/$Video_ID$/lm3d_radnerf.yaml --exp_name=$Video_ID$/lm3d_radnerf时出现该错误，使用的视频是自己提供的，利用剪辑软件将其调整为FPS=25，512*512，请问这种情况该怎么办，如何打印出错的帧

**Comment by muximuxi** [comment]
同问。应该是侧脸，检测到的嘴巴区域太小了，也就是说正脸图片就能正常处理，加了过滤条件，可以过滤侧脸，但是侧脸的这种情况该怎么解决？

**Comment by stevetatum** [comment]
> 同问。应该是侧脸，检测到的嘴巴区域太小了，也就是说正脸图片就能正常处理，加了过滤条件，可以过滤侧脸，但是侧脸的这种情况该怎么解决？
侧脸的话我也不太清楚。
我的原因可能是原来的视频长度可能不太够，不到三分钟，我现在换了个3分钟以上的，目前还在跑，暂时没有出现该错误。

**Comment by lokvke** [comment]
请问解决了吗，遇到了相同问题
