### ISSUE TITLE
RuntimeError: The expanded size of the tensor (50) must match the existing size (55) at non-singleton dimension 0.  Target sizes: [50, 44].  Tensor sizes: [55, 44]

### ISSUE THREAD

**Issue by tito-dt** [yerfor/GeneFace#228]
首先感谢作者的项目分享，然后我在尝试提取另外的特定人物特征的时候，即执行 python data_util/process.py --video_id=video_1_4 --task=2 时，报如下错误，已经在本项目中尝试找过类似问题，但没有找到，而且在尝试提取示例May.mp4的特征时，是没有问题的。请问该如何解决？
环境：
python  3.9.16
cuda 11.7

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/GeneFace/data_util/extract_esperanto.py", line 424, in <module>
    asr.run()
  File "/home/GeneFace/data_util/extract_esperanto.py", line 364, in run
    self.run_step()
  File "/home/GeneFace/data_util/extract_esperanto.py", line 222, in run_step
    self.feat_queue[start:end] = feats
RuntimeError: The expanded size of the tensor (50) must match the existing size (55) at non-singleton dimension 0.  Target sizes: [50, 44].  Tensor sizes: [55, 44]

**Comment by lokvke** [comment]
解决了吗，遇到相同问题了
RuntimeError: The expanded size of the tensor (50) must match the existing size (51) at non-singleton dimension 0.  Target sizes: [50, 44].  Tensor sizes: [51, 44]

**Comment by jackyin68** [comment]
only supports 512x512 and 25 fps videos

**Comment by aurelianocyp** [comment]
我的视频就是512*512和25fps的，但依旧出了这个问题，后来尝试了许多方法后觉得是视频的原音频有问题，于是在视频剪辑软件中将视频减掉了一小点，导出再进行处理，就成功了

**Comment by tito-dt** [comment]
> 我的视频就是512*512和25fps的，但依旧出了这个问题，后来尝试了许多方法后觉得是视频的原音频有问题，于是在视频剪辑软件中将视频减掉了一小点，导出再进行处理，就成功了

方便分享下具体的操作方法吗？  减掉一小点是指长度剪短么？

**Comment by aurelianocyp** [comment]
> > 我的视频就是512*512和25fps的，但依旧出了这个问题，后来尝试了许多方法后觉得是视频的原音频有问题，于是在视频剪辑软件中将视频减掉了一小点，导出再进行处理，就成功了
> 
> 方便分享下具体的操作方法吗？ 减掉一小点是指长度剪短么？

是的，就是随便找个视频剪辑软件，将视频拖到时间轴上，然后减掉个一秒或者零点几秒或者一秒多都行，然后导出，处理导出的视频就不会报这个错了。我使用的是万兴喵影软件。

**Comment by tito-dt** [comment]
> > > 我的视频就是512*512和25fps的，但依旧出了这个问题，后来尝试了许多方法后觉得是视频的原音频有问题，于是在视频剪辑软件中将视频减掉了一小点，导出再进行处理，就成功了
> > 
> > 
> > 方便分享下具体的操作方法吗？ 减掉一小点是指长度剪短么？
> 
> 是的，就是随便找个视频剪辑软件，将视频拖到时间轴上，然后减掉个一秒或者零点几秒或者一秒多都行，然后导出，处理导出的视频就不会报这个错了。我使用的是万兴喵影软件。

请问下，视频总长度是多少秒的？

**Comment by aurelianocyp** [comment]
> > > > 我的视频就是512*512和25fps的，但依旧出了这个问题，后来尝试了许多方法后觉得是视频的原音频有问题，于是在视频剪辑软件中将视频减掉了一小点，导出再进行处理，就成功了
> > > 
> > > 
> > > 方便分享下具体的操作方法吗？ 减掉一小点是指长度剪短么？
> > 
> > 
> > 是的，就是随便找个视频剪辑软件，将视频拖到时间轴上，然后减掉个一秒或者零点几秒或者一秒多都行，然后导出，处理导出的视频就不会报这个错了。我使用的是万兴喵影软件。
> 
> 请问下，视频总长度是多少秒的？

我本来是4：00，然后报错，说是Tensor sizes: [53, 44]，剪成3：59了，就成了。之前没尝试过剪，只尝试过导出的时候更改各种参数，包括采样率之类的，试了十多个视频发现没用。剪了一下就有用了。

**Comment by zxs-learn** [comment]
> extract_esperanto



> > > 我的视频就是512*512和25fps的，但依旧出了这个问题，后来尝试了许多方法后觉得是视频的原音频有问题，于是在视频剪辑软件中将视频减掉了一小点，导出再进行处理，就成功了
> > 
> > 
> > 方便分享下具体的操作方法吗？ 减掉一小点是指长度剪短么？
> 
> 是的，就是随便找个视频剪辑软件，将视频拖到时间轴上，然后减掉个一秒或者零点几秒或者一秒多都行，然后导出，处理导出的视频就不会报这个错了。我使用的是万兴喵影软件。

我直接 改成 self.feat_queue[start:end] = feats[:50] 了， 不知道对效果有没有影响。
