### ISSUE TITLE
Req Docker image

### ISSUE THREAD

**Issue by samsgates** [yerfor/GeneFace#23]
any one have Docker file to qucik environment setup ? it's seems like existing pytorch3d version not supported RTX3050

**Comment by yerfor** [comment]
Hi, for your convenience, below are my library versions of RTX3090:

> \# Name Version Build Channel
> pytorch 1.11.0 py3.7_cuda11.3_cudnn8.2.0_0 pytorch
> cudatoolkit 11.3.1 h2bc3f7f_2 defaults
> pytorch3d 0.6.2 py37_cu113_pyt1110 pytorch3d
> torchaudio 0.11.0+cu113 pypi_0 pypi
> torchvision 0.12.0+cu113 pypi_0 pypi

Hopefully, this may help you out.
