### ISSUE TITLE
some questions about dataset

### ISSUE THREAD

**Issue by hylq66** [yerfor/GeneFace#24]
This is an excellent work, I have some questions to consult
1. Is it necessary to first train a basic model with LRS3 data set, and then use eight target person videos for fine-tuning?
2. Can you share the processed LRS3 data set?

**Comment by yerfor** [comment]
Hi,

>  At the first step, you use LRS3 dataset to train a  generic audio2motion model and syncnet model. Then you use LRS3 and a target person video to train a person-specific postnet model. Finally you use the target person video to train the Head nerf and torso nerf.
> Yes, please refer to the download link in docs/process_data/process_lrs3.md

**Comment by hylq66** [comment]
Thanks!
