### ISSUE TITLE
Dataset Related Question

### ISSUE THREAD

**Issue by G-1nOnly** [yerfor/GeneFace#25]
First off thanks for the great work. 
The LRS preprocessed dataset is currently on Baidu Netdisk, which is hard to download due to the low speed. Could you upload it to other net disks like aliyunpan so that we could download it at a faster speed? 
Thanks in advance.

**Comment by G-1nOnly** [comment]
Thank you for your response, then perhaps google drive?

**Comment by yerfor** [comment]
Since the `zip` is quite large (~35GB), it exceed the free capacity of Google Drive (only 15GB).

**Comment by G-1nOnly** [comment]
Thanks then.

**Comment by yerfor** [comment]
Hi, I have uploaded the new processed lrs3 dataset (~25GB) on Google Drive. The download link is provided in the `docs/process_data/process_lrs3.md`.

**Comment by hylq66** [comment]
Hello, is the resolution of the processed LR3 dataset 224*224? Can you share the LR3 dataset in the processed video format?

> Hi, I have uploaded the new processed lrs3 dataset (~25GB) on Google Drive. The download link is provided in the `docs/process_data/process_lrs3.md`.
Hello, is the resolution of the processed LR3 dataset 224*224? Could you share the LR3 dataset in the processed video format?

**Comment by yerfor** [comment]
Yes, the resolution of raw lrs3 video is 224x224. We cannot provide the video format because of the license issue. Still, the provided processed dataset file contains all features needed to train GeneFace.

**Comment by hylq66** [comment]
Thanks.
