### ISSUE TITLE
Dear teachers who have seen this message, may I ask why the command "conda install pytorch3d - c pytorch3d - y # 0.7.2 recommended" in the Python library provided by the author always fails to find the download package in the channel on the Windows terminal? Is there any way to solve this problem?

### ISSUE THREAD

**Issue by peicee** [yerfor/GeneFace#256]
<img width="858" alt="屏幕截图 2024-01-06 221439" src="https://github.com/yerfor/GeneFace/assets/155707974/71b14706-c973-4a22-9656-39d814bc496b">

<img width="863" alt="屏幕截图 2024-01-06 221516" src="https://github.com/yerfor/GeneFace/assets/155707974/930f7cb6-e60c-4709-8bc7-0e9416737583">

**Comment by yerfor** [comment]
Hi, we have released the code of GeneFace++ (https://github.com/yerfor/GeneFacePlusPlus). We recommend you turn to this upgraded version for better performance. In the GeneFace++ could, we change the way to install pytorch3d with `pip install`
