### ISSUE TITLE
安培架构GPU（如RTX 3090）环境版本冲突

### ISSUE THREAD

**Issue by st01tyy** [yerfor/GeneFace#26]
您好，根据环境安装教程`docs/prepare_env/zh/install_guide_nerf.md`，如RTX 3090的安培架构GPU需要安装cuda 11.2，但是根据anacodna官网给出的信息：https://anaconda.org/pytorch3d/pytorch3d/files?sort=basename&version=0.6.2&sort_order=desc
pytorch3d 0.6.2版本仅支持cuda 11.1或cuda 11.3，没有对应cuda 11.2的版本。
与此同时，安培架构GPU的最低CUDA版本是cuda 11.1，故英文版本的教程中的cuda 11.0也有问题。
除此之外，pytorch3d 0.6.2的所有py3.8_cuda11.x版本中，最低的pytorch版本为1.10.1，故教程中的pytorch 1.7.1也不对

**Comment by yerfor** [comment]
Hi, thanks for pointing out that! The guide is mainly intended for rtx2080. I will update the installation_guide on rtx3090.

For your convenience, below are my library versions of RTX3090:
> \# Name                    Version                   Build                Channel
> pytorch                   1.11.0          py3.7_cuda11.3_cudnn8.2.0_0    pytorch 
> cudatoolkit               11.3.1               h2bc3f7f_2    defaults
> pytorch3d                 0.6.2           py37_cu113_pyt1110    pytorch3d
> torchaudio                0.11.0+cu113             pypi_0    pypi
> torchvision               0.12.0+cu113             pypi_0    pypi

Hopefully, this may help you out.

**Comment by st01tyy** [comment]
Hi, thanks for your reply, referring to your environment, I seem to be able to run your model successfully. But when running script `bash scripts/infer_postnet.sh` with reference to README, I encountered an error that the file could not be found:
`FileNotFoundError: [Errno 2] No such file or directory: 'data_util/BFM_models/BFM_model_front.mat'`

**Comment by yerfor** [comment]
Hi, please refer to the download link in section `1.3` of `docs/prepare_env/install_guide_lrs3.md`

**Comment by st01tyy** [comment]
Thank you for your reply. Are the other steps of this tutorial `docs/prepare_env/install_guide_lrs3.md` necessary to run the Quick Start successfully?

**Comment by hylq66** [comment]
> 

Hi, is the same for the process_lrs3 environment configuration？

**Comment by st01tyy** [comment]
I successfully ran script `bash scripts/infer_postnet.sh`, but encountered the following error when running script `bash scripts/infer_lm3d_nerf.sh`
```
The deepspeech extracted successfully, saved at:  data/raw/val_wavs/zozo_16k_deepspeech.npy
The shape is:  (272, 16, 29)
Saved deepspeech features of data/raw/val_wavs/zozo_16k.wav to data/raw/val_wavs/zozo_16k_deepspeech.npy.
Loaded deepspeech features from data/raw/val_wavs/zozo_16k_deepspeech.npy.
| Unknow hparams:  []
The eye blink mode is: gt
Traceback (most recent call last):
  File "inference/nerfs/lm3d_nerf_infer.py", line 146, in <module>
    LM3dNeRFInfer.example_run(inp)
  File "/workspace/GeneFace/inference/nerfs/base_nerf_infer.py", line 292, in example_run
    infer_ins.infer_once(inp)
  File "/workspace/GeneFace/inference/nerfs/base_nerf_infer.py", line 256, in infer_once
    samples = self.get_cond_from_input(inp)
  File "inference/nerfs/lm3d_nerf_infer.py", line 110, in get_cond_from_input
    mel, energy = get_mel_from_fname(self.wav16k_name, return_energy=True)
  File "/workspace/GeneFace/data_util/extract_mel.py", line 29, in get_mel_from_fname
    mel_basis = librosa.filters.mel(sample_rate, fft_size, num_mels, fmin, fmax)
TypeError: mel() takes 0 positional arguments but 5 were given
```
I installed librosa with conda instead of pip which mentioned in the tutorial `docs/prepare_env/install_guide_nerf.md`. Is this the cause of the error?

**Comment by yerfor** [comment]
> > @yerfor
> 
> Hi, is the same for the process_lrs3 environment configuration？

Yes. I will update the installation guide for process_lrs3 environment accordingly.

**Comment by yerfor** [comment]
> I successfully ran script `bash scripts/infer_postnet.sh`, but encountered the following error when running script `bash scripts/infer_lm3d_nerf.sh`
> 
> ```
> The deepspeech extracted successfully, saved at:  data/raw/val_wavs/zozo_16k_deepspeech.npy
> The shape is:  (272, 16, 29)
> Saved deepspeech features of data/raw/val_wavs/zozo_16k.wav to data/raw/val_wavs/zozo_16k_deepspeech.npy.
> Loaded deepspeech features from data/raw/val_wavs/zozo_16k_deepspeech.npy.
> | Unknow hparams:  []
> The eye blink mode is: gt
> Traceback (most recent call last):
>   File "inference/nerfs/lm3d_nerf_infer.py", line 146, in <module>
>     LM3dNeRFInfer.example_run(inp)
>   File "/workspace/GeneFace/inference/nerfs/base_nerf_infer.py", line 292, in example_run
>     infer_ins.infer_once(inp)
>   File "/workspace/GeneFace/inference/nerfs/base_nerf_infer.py", line 256, in infer_once
>     samples = self.get_cond_from_input(inp)
>   File "inference/nerfs/lm3d_nerf_infer.py", line 110, in get_cond_from_input
>     mel, energy = get_mel_from_fname(self.wav16k_name, return_energy=True)
>   File "/workspace/GeneFace/data_util/extract_mel.py", line 29, in get_mel_from_fname
>     mel_basis = librosa.filters.mel(sample_rate, fft_size, num_mels, fmin, fmax)
> TypeError: mel() takes 0 positional arguments but 5 were given
> ```
> 
> I installed librosa with conda instead of pip which mentioned in the tutorial `docs/prepare_env/install_guide_nerf.md`. Is this the cause of the error?

It seems to be a version problem of Librosa. I will check it later.

**Comment by JamesLong199** [comment]
> I successfully ran script `bash scripts/infer_postnet.sh`, but encountered the following error when running script `bash scripts/infer_lm3d_nerf.sh`
> 
> ```
> The deepspeech extracted successfully, saved at:  data/raw/val_wavs/zozo_16k_deepspeech.npy
> The shape is:  (272, 16, 29)
> Saved deepspeech features of data/raw/val_wavs/zozo_16k.wav to data/raw/val_wavs/zozo_16k_deepspeech.npy.
> Loaded deepspeech features from data/raw/val_wavs/zozo_16k_deepspeech.npy.
> | Unknow hparams:  []
> The eye blink mode is: gt
> Traceback (most recent call last):
>   File "inference/nerfs/lm3d_nerf_infer.py", line 146, in <module>
>     LM3dNeRFInfer.example_run(inp)
>   File "/workspace/GeneFace/inference/nerfs/base_nerf_infer.py", line 292, in example_run
>     infer_ins.infer_once(inp)
>   File "/workspace/GeneFace/inference/nerfs/base_nerf_infer.py", line 256, in infer_once
>     samples = self.get_cond_from_input(inp)
>   File "inference/nerfs/lm3d_nerf_infer.py", line 110, in get_cond_from_input
>     mel, energy = get_mel_from_fname(self.wav16k_name, return_energy=True)
>   File "/workspace/GeneFace/data_util/extract_mel.py", line 29, in get_mel_from_fname
>     mel_basis = librosa.filters.mel(sample_rate, fft_size, num_mels, fmin, fmax)
> TypeError: mel() takes 0 positional arguments but 5 were given
> ```
> 
> I installed librosa with conda instead of pip which mentioned in the tutorial `docs/prepare_env/install_guide_nerf.md`. Is this the cause of the error?

I encountered the same issue with librosa=0.10.0, the relevant discussion can be found [here](https://github.com/librosa/librosa/issues/1444). To fix it, pass all arguments by keywords:

mel_basis = librosa.filters.mel(sr=sample_rate,
                                    n_fft=fft_size,
                                    n_mels=num_mels,
                                    fmin=fmin,
                                    fmax=fmax)

**Comment by davidmartinrius** [comment]
> > I successfully ran script `bash scripts/infer_postnet.sh`, but encountered the following error when running script `bash scripts/infer_lm3d_nerf.sh`
> > ```
> > The deepspeech extracted successfully, saved at:  data/raw/val_wavs/zozo_16k_deepspeech.npy
> > The shape is:  (272, 16, 29)
> > Saved deepspeech features of data/raw/val_wavs/zozo_16k.wav to data/raw/val_wavs/zozo_16k_deepspeech.npy.
> > Loaded deepspeech features from data/raw/val_wavs/zozo_16k_deepspeech.npy.
> > | Unknow hparams:  []
> > The eye blink mode is: gt
> > Traceback (most recent call last):
> >   File "inference/nerfs/lm3d_nerf_infer.py", line 146, in <module>
> >     LM3dNeRFInfer.example_run(inp)
> >   File "/workspace/GeneFace/inference/nerfs/base_nerf_infer.py", line 292, in example_run
> >     infer_ins.infer_once(inp)
> >   File "/workspace/GeneFace/inference/nerfs/base_nerf_infer.py", line 256, in infer_once
> >     samples = self.get_cond_from_input(inp)
> >   File "inference/nerfs/lm3d_nerf_infer.py", line 110, in get_cond_from_input
> >     mel, energy = get_mel_from_fname(self.wav16k_name, return_energy=True)
> >   File "/workspace/GeneFace/data_util/extract_mel.py", line 29, in get_mel_from_fname
> >     mel_basis = librosa.filters.mel(sample_rate, fft_size, num_mels, fmin, fmax)
> > TypeError: mel() takes 0 positional arguments but 5 were given
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I installed librosa with conda instead of pip which mentioned in the tutorial `docs/prepare_env/install_guide_nerf.md`. Is this the cause of the error?
> 
> I encountered the same issue with librosa=0.10.0, the relevant discussion can be found [here](https://github.com/librosa/librosa/issues/1444). To fix it, pass all arguments by keywords:
> 
> mel_basis = librosa.filters.mel(sr=sample_rate, n_fft=fft_size, n_mels=num_mels, fmin=fmin, fmax=fmax)

This solved the problem for me. Thank you! :smile:
