### ISSUE TITLE
ModuleNotFoundError: No module named '_raymarching_face'

### ISSUE THREAD

**Issue by ChengsongLu** [yerfor/GeneFace#262]
Traceback (most recent call last):
  File "/home/lll/x/GeneFace/modules/radnerfs/raymarching/raymarching.py", line 10, in <module>
    import _raymarching_face as _backend
ModuleNotFoundError: No module named '_raymarching_face'

**Comment by yerfor** [comment]
Hi, you should run `bash docs/prepare_env/install_ext.sh` to install the torch-ngp extension first.

Besides, we have released the code of GeneFace++ (https://github.com/yerfor/GeneFacePlusPlus). We recommend you turn to this upgraded version for better performance.

**Comment by tranthuhoai3786** [comment]
conda install pytorch==1.12.0 torchvision==0.13.0 torchaudio==0.12.0 cudatoolkit=11.6 -c pytorch -c conda-forge
it works for me, cuda 11.6 and pytorch 1.12
@ChengsongLu
