### ISSUE TITLE
关于Error2的疑惑

### ISSUE THREAD

**Issue by hylq66** [yerfor/GeneFace#28]
Thanks for open source code. I have also encountered such a problem with the subject, and I have some questions about the error2 you mentioned in the link.https://github.com/yerfor/GeneFace/issues/2#issuecomment-1418775061

![image](https://user-images.githubusercontent.com/113688724/220810205-cae5af3f-d5f5-48d8-ae3d-995ccc8ccb71.png)

As you said before, you added -D_GLIBCXX_USE_CXX11_ABI=0, but the code you uploaded was commented out.
![image](https://user-images.githubusercontent.com/113688724/220810079-5993218b-0e5f-49e3-bdff-3c9001e8f956.png)

When I removed the comment, I reported more errors.
![image](https://user-images.githubusercontent.com/113688724/220810379-34d1a5b8-2e29-455f-aad9-aecd6618c573.png)
![image](https://user-images.githubusercontent.com/113688724/220810296-16df3833-1411-4a3e-a8dc-4dfea51b2a7c.png)

My environment is shown below, cuda11.3.
![image](https://user-images.githubusercontent.com/113688724/220810760-d6790324-433e-4ea1-ae47-36184ecc6e2a.png)

Could you give me some advice on how to solve it?

**Comment by yerfor** [comment]
Hi, maybe you could place `-D_GLIBCXX_USE_CXX11_ABI=0` into the `cmd` argument, i.e., `xxx -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -I$$TF_INC xxx`

**Comment by yerfor** [comment]
I have also successfully re-installed mesh_render on RTX3080ti. Please follow the updated guide, which may help you out.

For your convenience, below are my environments and command lines.
<img width="684" alt="image" src="https://user-images.githubusercontent.com/48365204/220839942-91802c5f-3c2d-4ed5-a79f-5a3990aa6279.png">

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/48365204/220840164-d00e9b6d-d417-4de5-a503-2431cd418415.png">

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/48365204/220840182-71c53618-7ccf-41ef-a0b1-d7d10d0fae12.png">

Note that I also encountered `libtensflowframework not found` error, you can fix it with the updated guide.
