### ISSUE TITLE
deep_3drecon/network/FaceReconModel.pb文件无法找到

### ISSUE THREAD

**Issue by hylq66** [yerfor/GeneFace#30]
Hello, as shown in the following figure, the FaceReconModel.pb file is missing when the validation statement is executed.
![image](https://user-images.githubusercontent.com/113688724/220902407-e727c6c0-ff7b-4ce5-ba07-048a401d07ed.png)
![image](https://user-images.githubusercontent.com/113688724/220902893-8ae52631-5ee5-4d37-996f-9516758537e9.png)

**Comment by yerfor** [comment]
I'm sorry for missing the `deep_3drecon/network/FaceReconModel.pb` file. I have uploaded it to Google Drive, you can download it at [this link](https://drive.google.com/file/d/1xkzE9cCbCDlJcYUJ5DG43_gp1ybBsNLB/view?usp=share_link). I have also updated the installation guide accordingly.

**Comment by hylq66** [comment]
Thank you.
