### ISSUE TITLE
some questions about deep_3drecon.Reconstructor()

### ISSUE THREAD

**Issue by hylq66** [yerfor/GeneFace#31]
Hello, there are some problems when I was verifying. I am not sure whether it is related to the tensorflow version. I use the CPU version of tensorflow=1.14. How can I solve this?
![image](https://user-images.githubusercontent.com/113688724/220933708-0041198c-d95d-4a20-9332-4737e26a932e.png)

**Comment by yerfor** [comment]
It seems not to be a Error, maybe you could go ahead and find whether other steps go well.
