### ISSUE TITLE
提取NecRF所需的特征 过程中发生的问题

### ISSUE THREAD

**Issue by Free-D** [yerfor/GeneFace#32]
在不同gpu下面提取NecRF所需的特征过程中  `python data_util/process_data.py --id=$1 --step=6`这一步中出现的错误
平台
    V100-32G的错误是![image](https://user-images.githubusercontent.com/82027599/221087256-70ddfb0b-cc8b-4857-8faf-6e91d5ba242c.png)
平台
    1660s-6G的错误是![image](https://user-images.githubusercontent.com/82027599/221096621-20660c29-0152-430f-a6b3-25f370e4fd71.png)

**Comment by yerfor** [comment]
看起来似乎是显存不足，你使用的是示例里的`May.mp4`吗，我在RTX2080上处理过8分钟的视频也没有过OOM。或许是视频过长？

**Comment by Free-D** [comment]
视频长度是17: 30左右，大小约为1000MB

**Comment by Free-D** [comment]
在程序运行过程中好像没有占用很大的显存，大约占用了1GB左右

**Comment by yerfor** [comment]
或许你可以debug一下，我会持续跟进你的新进展

**Comment by Free-D** [comment]
我现在减少了视频的大小和长度，正在准备重新尝试

**Comment by Free-D** [comment]
使用示例里的`May.mp4`的话，是可以正常提取的，是不是对训练视频文件的格式有一些限制，比如视频长度，视频文件大小，视频分辨率

**Comment by yerfor** [comment]
你好，理论上不该有视频长度大小分辨率的限制，预处理代码会自动将视频缩放到512x512的分辨率。如果必要，你可以分步以此进行`process_data.sh`里的几个步骤，看看问题出在哪里

**Comment by Free-D** [comment]
你好，上面那一步找到了原因，是因为视频文件太大，所以显存不够用了。
然后目前我在下一步`步骤2. 从视频中提取HuBERT和3DMM特征`中遇到了新的问题
![image](https://user-images.githubusercontent.com/82027599/222028661-0270aa69-c517-48b5-b6d0-c6778df74565.png)
在这里系统会内存不足，并且杀掉进程，我现在的内存为32G，请问需要多大的内存才能正常运行并得到`hubert.npy`文件

**Comment by yerfor** [comment]
你好，我近期有空时会优化一下face tracker和hubert提取两个代码的显存和内存的利用。

**Comment by Free-D** [comment]
好的，感谢你的回答

**Comment by yerfor** [comment]
你好，我在最新的commit中优化了hubert的显存和内存利用：
- 之前默认采用cpu执行，目前改成了默认gpu。
- 之前没有添加no_grad导致始终有梯度累计没有被释放，这是内存爆炸的原因。

**Comment by Free-D** [comment]
你好，我现在已经走到了这一步
![image](https://user-images.githubusercontent.com/82027599/222677026-77bfe4af-d111-4de2-8ae5-8f4711d3a743.png)
，但是它给我报了这个错误，我不明白为什么，还要再请教一下

**Comment by Free-D** [comment]
错误在这里![image](https://user-images.githubusercontent.com/82027599/222677252-9810878b-4994-45c4-9f88-4556b659526f.png)
