### ISSUE TITLE
zozo_16k_deepspeech.npy file not created

### ISSUE THREAD

**Issue by mirrorsize2022** [yerfor/GeneFace#33]
No such file or directory: 'data/raw/val_wavs/zozo_16k_deepspeech.npy'

Try to extract deepspeech from data/raw/val_wavs/zozo_16k.wav...
sh: 1: python: not found
Saved deepspeech features of data/raw/val_wavs/zozo_16k.wav to data/raw/val_wavs/zozo_16k_deepspeech.npy.
Traceback (most recent call last):
  File "/home/ubuntu/Projects/GeneFace/inference/nerfs/lm3d_nerf_infer.py", line 146, in <module>
    LM3dNeRFInfer.example_run(inp)
  File "/home/ubuntu/Projects/GeneFace/inference/nerfs/base_nerf_infer.py", line 292, in example_run
    infer_ins.infer_once(inp)
  File "/home/ubuntu/Projects/GeneFace/inference/nerfs/base_nerf_infer.py", line 256, in infer_once
    samples = self.get_cond_from_input(inp)
  File "/home/ubuntu/Projects/GeneFace/inference/nerfs/lm3d_nerf_infer.py", line 46, in get_cond_from_input
    deepspeech_arr = np.load(deepspeech_name) # [T, w=16, c=29]
  File "/home/ubuntu/.local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))

**Comment by yerfor** [comment]
Hi, please run `python data_util/deepspeech_features/extract_ds_features.py --input=data/raw/val_wavs/zozo_16k.wav --output= data/raw/val_wavs/zozo_16k_deepspeech.npy` and see the output log. There may be some bugs when extracting deepspeech.

**Comment by mirrorsize2022** [comment]
Thanks

**Comment by mirrorsize2022** [comment]
Can you help with this 
AssertionError: Please set `infer_sil_ref_frame_idx` to the index of a frame with closed mouth in the GT dataset

**Comment by yerfor** [comment]
Hi, for `May.mp4` we select `infer_sil_ref_frame_idx=6072` (I have updated the new config file in the latest commit). To get `infer_sil_ref_frame_idx` for your own video, you need go to `data/processed/<video_id>/orig_imgs/` and select a image with closed mouth, then use the idx of this image as the value of `infer_sil_ref_frame_idx`.

**Comment by yerfor** [comment]
@mirrorsize2022 
Hi, what's your tensorflow version? In `data_util/deepspeech_features/deepspeech_features.py`, you can try comment the lines with `'deepspeech/logits:0'` and use `'logits:0'` instead. 
<img width="745" alt="image" src="https://user-images.githubusercontent.com/48365204/221362840-0c8d6dc3-624d-4b52-acae-adcf91b8b6f1.png">
