### ISSUE TITLE
infer_sil_ref_frame_idx

### ISSUE THREAD

**Issue by zyhsuperman** [yerfor/GeneFace#34]
请问按照quick start进行跑时，这个需要设置为多少呀"Please set `infer_sil_ref_frame_idx` to the index of a frame with closed mouth in the GT dataset"

**Comment by yerfor** [comment]
你好，进入`data/processed/<video_id>/orig_imgs/`里面，选择一帧紧闭嘴唇的图片，将其序号作为`infer_sil_ref_frame_idx`即可。对`May.mp4`来说，我们实验时采用的是`infer_sil_ref_frame_idx=6072`

**Comment by zyhsuperman** [comment]
好的，非常感谢！！

**Comment by kaankarakose** [comment]
Hello, I followed the quick start steps but I have same problem. However, there is no `data/processed/<video_id>/orig_imgs/` directory in the repo. Am I missing something?
Thank you for this work and I am appreciated if you can help me.

**Comment by kaankarakose** [comment]
Hello, I followed the quick start steps but I have same problem. However, there is no data/processed/<video_id>/orig_imgs/ directory in the repo. Am I missing something?
Thank you for this work and I am appreciated if you can help me.

**Comment by yerfor** [comment]
Hi, `data/processed/<video_id>/orig_imgs/` is generated when you are processing the NeRF dataset following `docs/process_data/process_target_person_video.md`.  If you are using `May.mp4`, you can directly use `6072` as default. 

By the way, to prevent confusion, in the latest commit, I have set the usage of `infer_sil_ref_frame_idx` as optional, so a pull may help you out.

**Comment by kaankarakose** [comment]
Thank you so much, latest commit is solved my problem.
