### ISSUE TITLE
quick start guide报错

### ISSUE THREAD

**Issue by wangyuyy** [yerfor/GeneFace#35]
按照`quick start`流程下载解压数据后，在运行指令`bash scirpts/infer_postnet.sh`时报错
<img width="715" alt="image" src="https://user-images.githubusercontent.com/106719785/221471406-14afc2a7-8ff5-4309-a780-8de7d0925e40.png">

**Comment by yerfor** [comment]
你好，这个bug是因为我将本地使用的script覆盖到了github的repo，目前我已经更新，请pull最新的代码就可以解决这个问题

**Comment by wangyuyy** [comment]
好的多谢！另外readme.md有个小小的问题，就是`quick start`部分`./deep_util/BFM_models`应为`./data_util/BFM_models`

**Comment by yerfor** [comment]
收到，感谢！
