### ISSUE TITLE
请教对中文的支持问题

### ISSUE THREAD

**Issue by kendo6666** [yerfor/GeneFace#36]
看到演示视频中，中文歌曲的口型生成非常棒。但是并没有使用deepspeech的中文模型来生成语音特征，请问这样做是跨语种的吗？任意语言都支持吗？

**Comment by yerfor** [comment]
可以的

**Comment by kendo6666** [comment]
> 可以，我们尝试过中文、英文、俄语等多种语言均可以得到准确的唇形。 不过，目前我们使用的是`hubert-large-ls960-ft`模型进行语音表征的提取，这个模型是在960小时的英文语音数据集上训练的，所以可能还是对英文的效果最为准确。如果有必要的话，可以尝试在训练audio2motion模块时，将hubert模型替换成对应语种的版本，可能会有更好的效果。

非常感谢你的回复，刚接触GeneFace，对它的代码还不太熟悉。
我看到process_data.py中第一步是调用extract_ds_features.py，使用deepspeech从wav中提取特征。但是process_audio_hubert.py中又使用了hubert-large-ls960-ft。它们之间是什么关系呢？

**Comment by yerfor** [comment]
我们的torso nerf沿用了ad-nerf的框架，所以deepspeech被用于torso nerf的额外condition，事实上这也是目前deepspeech在geneface整体流程中的唯一用途。相比之下，hubert则被用于audio2motion模型，作为语音表征。

**Comment by kendo6666** [comment]
谢谢指点，ad-nerf在AudioNet中使用卷积进行特征提取，我最初还以为Gene沿用了它的做法，现在经你这么一说，就都串起来了，感谢你们杰出的工作！！！
