### ISSUE TITLE
get_hubert_from_16k_speech 函数导出结果和音频文件帧数之间什么关系？

### ISSUE THREAD

**Issue by zhangziliang04** [yerfor/GeneFace#39]
感谢作者，第一次使用huBert，遇到个问题，请教一下：
使用deepspeech从wav中提取特征，每一帧音频对应要给特征组，如：# (5431, 16, 29)，其中5431代表帧数，29为采样点数。但是通过hubert获得数据shape却是一个二维的，如：(9050, 1024)，其中9050没有办法如5431一样，直接指向音频文件的帧数。

**Comment by yerfor** [comment]
你好，理想情况下，hubert提取得到的特征应该是视频帧数的两倍左右，比如示例中的`May.mp4`，你可以发现视频帧数为6073，而视频等长的音频的hubert特征的长度为12145。

请你检查一下提取hubert的过程是否有问题，比如音频/视频长度不一致。

**Comment by yerfor** [comment]
1. 提取hubert音频特征的代码经过特定设计，保持其fps=50，是视频帧率的2倍（对一个数分钟的音频来说差距不超过几个frames）。然后在audio2motion模块中，会有一个下采样操作将其变换到视频帧率。可以理解成提取的hubert中每两帧对应视频的一帧。
2. 如上所述，其实hubert已经和视频帧一一对应了，所以没有必要进一步做规范化。

**Comment by zhangziliang04** [comment]
@yerfor 感谢回复，终于弄明白了。之前一直在用deepspech，刚开始用hubert，这下搞清楚了。谢谢。

**Comment by zhangziliang04** [comment]
问题已解决，感谢。

**Comment by mazai-xiangji** [comment]
> 1. 提取hubert音频特征的代码经过特定设计，保持其fps=50，是视频帧率的2倍（对一个数分钟的音频来说差距不超过几个frames）。然后在audio2motion模块中，会有一个下采样操作将其变换到视频帧率。可以理解成提取的hubert中每两帧对应视频的一帧。
> 
>     2. 如上所述，其实hubert已经和视频帧一一对应了，所以没有必要进一步做规范化。

你好，我想知道处理hubert特征使其与视频帧数对应的代码在哪个部分

**Comment by yerfor** [comment]
不好意思，目前仅支持25fps。如果要修改成fps30，可能需要同时修改audio2motion的数据处理

**Comment by yerfor** [comment]
kernel和stride是由预训练的hubert模型决定的，如果要对齐的话，你可以用torch的F.interpolate实现这个功能

**Comment by yerfor** [comment]
可以的，不过我用的是默认的nearest，因为hubert的特征可能不是线性可插值的

**Comment by mazai-xiangji** [comment]
好的，感谢你的耐心回复！
