### ISSUE TITLE
 questions about process_lrs3 environment 

### ISSUE THREAD

**Issue by jackiezhang11** [yerfor/GeneFace#41]
environment:
RTX3090
cuda 11.1
tensorflow-gpu 1.14
bazel:1.00

command: sudo ./bazel-1.0.0-installer-linux-x86_64.sh
cd deep_3drecon/mesh_renderer/
touch WORKSPACE
bazel build //kernels:rasterize_triangles_kernel 

export PYTHONPATH=./
CUDA_VISIBLE_DEVICES=0 python 
> import deep_3drecon

![微信图片_20230303161758](https://user-images.githubusercontent.com/59191325/222668265-4a4417b4-16ec-47c9-a763-3b919a27ab8a.png)

**Comment by yerfor** [comment]
Hi, as you use RTX3090, on which TF1.14-GPU cannot work, maybe you could try tensorflow=1.14 (cpu version).

Following the newest `docs/prepare_env/install_guide_lrs3.md` may help you out.

**Comment by jackiezhang11** [comment]
I have installed TF-gpu1.14 and TF1.14

**Comment by jackiezhang11** [comment]
OK ,I have fix it.Thanks

**Comment by jackiezhang11** [comment]
another question occured.could you konw how to fix it 
astor vesion:0.6.2
def visit_FunctionDef(self, node, async=False):     'line 311
      prefix = 'async ' if async else '

SyntaxError: invalid syntax

**Comment by yerfor** [comment]
could you provide more details, such as your input command line, and the output screenshot?

**Comment by jackiezhang11** [comment]
ok ,details as follow picture.
![微信图片_20230303171125](https://user-images.githubusercontent.com/59191325/222679831-7224d290-11c7-4d1e-88c7-b4d1a1200de9.png)

**Comment by yerfor** [comment]
it seems to be a error when import tensorflow, maybe you could check the installation of tensorflow

**Comment by jackiezhang11** [comment]
OK.. I use o new environment .But occured a new BUG.Do as you write.not use.
error:
libtensorflow_framework.so.2:cannot open shared object file

**Comment by jackiezhang11** [comment]
As for me , It is not working!
