### ISSUE TITLE
请问一下如何做到中文语音驱动像示例视频差不多的效果

### ISSUE THREAD

**Issue by TSITMN** [yerfor/GeneFace#42]
这是我跑出来的效果

https://user-images.githubusercontent.com/70303988/222914320-244d3b2a-1f86-444f-bf43-4f6072b8a227.mp4

**Comment by yerfor** [comment]
你好，geneface的推理流程是audio2motion模块==>postnet模块==>nerf渲染，如果最终的嘴形结果不准确，你可以依次排查是哪个流程出了问题。

我的建议是，首先使用`utils/visualization/lm_visualizer.py`可视化postnet预测的人脸动作，看看嘴形是否准确。如果准确，则进入下一步，在`inference/lm3d_nerf_infer.py`中的60-80行记录了三阶段的对postnet预测的landmark的后处理流程。你可以尝试将`step1. clamp the lm3d, to regularize apparent outliers`部分的代码注释，或者增大clamp的上下界，以减小对landmark的限制；你也可以将`step2. LLE projection to drag the predicted lm3d closer to the GT lm3d`部分的代码注释或者调小`hparams['infer_lm3d_lle_percent']`（默认是0.5），以减少对landmarkd的修整；你还可以在`step3. gaussian filter to smooth the whole sequence`将hparams['infer_lm3d_smooth_sigma']调小，或者调整为0，以减少平滑效果。

以上四个调整的方法你都可以尝试一下。期待你调好效果的消息。

**Comment by zhangziliang04** [comment]
遇到同样的问题，目前看最主要的问题是：1.动作幅度过大，脖子有一个明显的拉伸过程。感觉还是安安静静的效果会更好。有时间，我也实测一下。

**Comment by yerfor** [comment]
你好，脖子拉伸的问题是因为我们采用的是GT的pose，可能在May视频中开头部分pose动作幅度比较大，和大多数音频对齐的时候显得不够自然。如果你想要安静的pose的话，可以从gt pose中选择相对安静的slice（比如在inference/get_pose_from_ds从ds中index的时候加一个offset）。

**Comment by zhangziliang04** [comment]
@yerfor 感谢回复，我实测一下看看效果。已经是这个项目的深度用户，不知道能不能加一下微信，我的：zhangziliang04,手机号：13718542435

**Comment by jackiezhang11** [comment]
可以不重新训练得到只有嘴在说话的效果吗？

**Comment by yerfor** [comment]
> 可以不重新训练得到只有嘴在说话的效果吗？

如果你的意思是只渲染头部而不渲染身躯，你可以将inference script里面的`lm3d_nerf_torso/config.yaml`替换成`lm3d_nerf/config.yaml` 。如果你的意思是像Wav2Lip那样只合成唇部图像的话，我们近期暂时没有实现这个功能的打算。

**Comment by jackiezhang11** [comment]
我的意思是不管是都渲染还是只渲染头部，不让头左右晃动，说话时，保持头部是正面且微笑的姿势。

**Comment by yerfor** [comment]
你可以通过以下方法来实现这个需求：

修改`inference/nerfs/base_nerf_infer.py`的`get_pose_from_ds`， 将`sample['c2w']`、`sample['euler']`、`sample['trans']`替换成dataset中的第一帧数据。

**Comment by Gpwner** [comment]
@yerfor 将 inference script里面的lm3d_nerf_torso/config.yaml替换成lm3d_nerf/config.yaml，输出视频只有头部。请问现在的代码是否能支持在只渲染头部的时候自动拼接上torso的真值，也即输出的视频帧为head_predict+torso_gt,感谢~

**Comment by yerfor** [comment]
Q1: 关于只渲染头部而使用gt torso
你可以把sample['bg_img'] = ds_sample['bg_img']替换成sample['bg_img'] = ds_sample['torso_img']

Q2:
你可以将rays_o改成self.dataset[0]['rays_o'], rays_d改成self.dataset[0]['rays_d'], pose改成self.dataset[0]['pose']

**Comment by Gpwner** [comment]
@yerfor 实测发现头部还会不自然地小幅度前倾 or 后仰（训练视频无类似素材）。运行radnerf_gui.py,发现可以拖拽实现头部小幅度前倾和后仰，请问能否有办法固定住每一推理帧头部的前倾 or 后仰 角度，使得推理结果看起来更为自然一些，感谢。

**Comment by yerfor** [comment]
可能是因为lm3d的204维度过大，使lm3d_radnerf在pose不变的情况下，实际渲染的结果依然有些pose抖动。我之前没有考虑过使头部静止，但我有两个可以尝试的解决方法。
第一，你可以试试smooth除了唇部以外的lm3d，（这部分代码在lm3d_nerf_infer.py里面有），或者将唇部以外的lm3d替换成第一帧的data。

第二，或许你可以尝试减小lm3d_radnerf的输入维度（比如只使用唇部的lm3d作为radnerf的condition），应该也可以得到更加稳定的效果（以略微减弱psnr为代价）

**Comment by muximuxi** [comment]
> 可能是因为lm3d的204维度过大，使lm3d_radnerf在pose不变的情况下，实际渲染的结果依然有些pose抖动。我之前没有考虑过使头部静止，但我有两个可以尝试的解决方法。 第一，你可以试试smooth除了唇部以外的lm3d，（这部分代码在lm3d_nerf_infer.py里面有），或者将唇部以外的lm3d替换成第一帧的data。
> 
> 第二，或许你可以尝试减小lm3d_radnerf的输入维度（比如只使用唇部的lm3d作为radnerf的condition），应该也可以得到更加稳定的效果（以略微减弱psnr为代价）

请教一下：修改了lm3d_radnerf_infer.py中，将rays_o，rays_d, pose都改成了self.dataset[0]['XXX'], 请问你说的这两部分具体哪里修改，不知道是不是改错了地方，按照上述两点修改后，晃动还是很厉害。谢谢~

**Comment by stevetatum** [comment]
> 好的，谢谢。我按您说的跑，生成的图是我想要的。
请问，在修改inference/nerfs/base_nerf_infer.py的get_pose_from_ds， 将sample['c2w']、sample['euler']、sample['trans']替换成dataset中的第一帧数据。 
dataset的第一帧数据在哪里，如何获得
