### ISSUE TITLE
请问音频停顿时嘴唇是否会保持闭合？有测试过这种情况嘛

### ISSUE THREAD

**Issue by Hothin** [yerfor/GeneFace#44]

**Comment by yerfor** [comment]
大多数情况下，audio2motion可以正确学到在静音帧时紧闭嘴唇。不过为了解决偶尔出现的静音帧没有闭上嘴唇的情况，我们在inference/nerfs模块里也根据静音情况对landmark做了后处理，具体的实现你可以参考一下inference/nerfs/lm3d_nerf_infer.py 里面的step5。这个功能默认是关闭的，如果你发现在你的case中出现了这样的bad case可以启用它。

**Comment by Hothin** [comment]
> 大多数情况下，audio2motion可以正确学到在静音帧时紧闭嘴唇。不过为了解决偶尔出现的静音帧没有闭上嘴唇的情况，我们在inference/nerfs模块里也根据静音情况对landmark做了后处理，具体的实现你可以参考一下inference/nerfs/lm3d_nerf_infer.py 里面的step5。这个功能默认是关闭的，如果你发现在你的case中出现了这样的bad case可以启用它。

谢谢你的回答，我还有个疑问，请问audio2motion是如何学到嘴唇紧闭的，LRS3数据集好像不存在静默的视频

**Comment by yerfor** [comment]
一方面可能是lrs3数据集比较大，另一方面可能是因为目标人数据集里有短暂的静默片段。不过由于数据集里没有长时间静默的视频，所以这之后可能需要后处理手段介入一下。
