### ISSUE TITLE
训练NeRF过程中的问题

### ISSUE THREAD

**Issue by Free-D** [yerfor/GeneFace#46]
在执行下面代码的时候遇到了错误，不明白是为什么，是前期训练的模型有什么问题吗
![image](https://user-images.githubusercontent.com/82027599/223014308-fb3b98b5-ebe5-48d7-9b3a-31677983b9bf.png)

错误：RuntimeError: shape '[5, 1, -1]' is invalid for input of size 26112
![image](https://user-images.githubusercontent.com/82027599/223014483-91561dce-4f24-4e9b-9a98-879cc27273b5.png)

**Comment by yerfor** [comment]
你好，原因似乎是binarize的时候提取的cond_win和预期的cond_win_size不符合。我排查了一下原因在于中文文档binarize的命令有误。在最新的commit中已经修正。请执行以下代码重新binarize：`python data_gen/nerf/binarizer.py --config=egs/datasets/videos/May/lm3d_nerf.yaml`。

**Comment by Free-D** [comment]
好的，感谢您的回答，在重新打包数据后已经能够正常训练基于NeRF的渲染器了
