### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by Free-D** [yerfor/GeneFace#47]
您好，请问我现在是32G的内存，一直会爆内存不足，请问您的配置是什么，好让我有个参考，谢谢

**Comment by yerfor** [comment]
你好，我使用的机器内存是256GB。可以提供一下详情，是在运行哪些命令时内存不足呢？以方便我检查一下对应的代码，修改以支持内存较小的机器。

**Comment by Free-D** [comment]
![image](https://user-images.githubusercontent.com/82027599/223023987-88616f65-2535-47af-b2d1-92a16b428af7.png)
是在上面的第一步中出现的内存不足，第二步还没有尝试，我的机器配置是，32G内存，3080ti-12G，i7-10700k

**Comment by yerfor** [comment]
这可能是因为训练nerf时为了避免图片io导致的减速，我默认会将读取的图片存在内存中，在内存不大的电脑中会导致内存不足。

在未来的一个commit我会提供一个config选项，你将可以选择是否将图片存在内存中。

**Comment by yerfor** [comment]
你好，可否记录一下运行程序时的内存占用情况？我在服务器上训练时显示内存占用不超过15GB

**Comment by Free-D** [comment]
这是拉取最新代码并且训练了16分钟的情况，在训练到17分钟左右，7000多step，内存实际占用到28G就会被杀掉进程
![7916cfde23feaed278f17c4f2990d34](https://user-images.githubusercontent.com/82027599/223298002-08569b79-9498-4145-b8ee-5aebf2c4e185.png)

**Comment by yerfor** [comment]
我之前没有遇到这样的情况，或许你可以debug一下定位一下占用内存大的部分？
