### ISSUE TITLE
Error in process_target_person_video

### ISSUE THREAD

**Issue by NoHateAnymore** [yerfor/GeneFace#5]
Thx for your contribution!!!

I had some problems when I run code "CUDA_VISIBLE_DEVICES=0 python data_gen/nerf/extract_hubert.py --video_id=$VIDEO_ID" in process_target_person_video. 

Loading the Wav2Vec2 Processor...
Loading the HuBERT Model...
Traceback (most recent call last):
  File "/home/gammalab/anaconda3/envs/process_lrs3/lib/python3.7/site-packages/transformers/modeling_utils.py", line 1348, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location="cpu")
  File "/home/gammalab/anaconda3/envs/process_lrs3/lib/python3.7/site-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/home/gammalab/anaconda3/envs/process_lrs3/lib/python3.7/site-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f8579ac7193 in /home/gammalab/anaconda3/envs/process_lrs3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f857cc4f9eb in /home/gammalab/anaconda3/envs/process_lrs3/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f857cc50c04 in /home/gammalab/anaconda3/envs/process_lrs3/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6c6536 (0x7f85c4b81536 in /home/gammalab/anaconda3/envs/process_lrs3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x295a74 (0x7f85c4750a74 in /home/gammalab/anaconda3/envs/process_lrs3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #53: __libc_start_main + 0xf3 (0x7f85d6559083 in /lib/x86_64-linux-gnu/libc.so.6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gammalab/anaconda3/envs/process_lrs3/lib/python3.7/site-packages/transformers/modeling_utils.py", line 1352, in from_pretrained
    if f.read().startswith("version"):
  File "/home/gammalab/anaconda3/envs/process_lrs3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "data_gen/nerf/extract_hubert.py", line 4, in <module>
    from data_gen.process_lrs3.process_audio_hubert import get_hubert_from_16k_speech
  File "/home/gammalab/CS/TalkingHeadGeneration/GeneFace/data_gen/process_lrs3/process_audio_hubert.py", line 9, in <module>
    hubert_model = HubertModel.from_pretrained("facebook/hubert-large-ls960-ft")
  File "/home/gammalab/anaconda3/envs/process_lrs3/lib/python3.7/site-packages/transformers/modeling_utils.py", line 1362, in from_pretrained
    f"Unable to load weights from pytorch checkpoint file for '{pretrained_model_name_or_path}' "
OSError: Unable to load weights from pytorch checkpoint file for 'facebook/hubert-large-ls960-ft' at '/home/gammalab/.cache/huggingface/transformers/3964c36efc75c1687db64aaf1d970beee48cd89e4a8c6b5bd072ca7ee9ff8cc5.bb6f85ae361fc3c32f100ac2335b4609e9f7135ced8e598265e36654b51d8471'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

I created "process_lrs3" environment by "pip install -r requirements_lrs3.txt", and torch=1.4.0 , is this torch version too old for this programs or any other problems? 

THX!!!!

**Comment by yerfor** [comment]
Thanks for pointing out this problem! 

Yes, it seems that the torch version is too old for transformers. Maybe you could use `conda activate geneface`, which use torch=1.7.1 instead. I have update the docs in the latest commit [3acc462](https://github.com/yerfor/GeneFace/commit/3acc462d8c8c4bca5b898eec829905083977f3a9)
