### ISSUE TITLE
处理数据问题

### ISSUE THREAD

**Issue by jackiezhang11** [yerfor/GeneFace#50]
提取3DMM时会出现不能调用GPU问题。
我的配置是RTX3090，环境是tensorflow1.14，没有配置GPU版本，是不是需要把提取3DMM过程中用到的所有代码都改成调用CPU。

![微信图片_20230308174847](https://user-images.githubusercontent.com/59191325/223679785-d61e889c-df29-48c6-bcc2-4bf170f0dce2.jpg)

在另一个类似conda环境，会出现另一个BUG，调用读取了视频，却会出现识别不到人脸Caught error at 0或者是fa.get_lanmarks done,error cnt:0:7000这样的错误，

**Comment by yerfor** [comment]
是的，我目前是在2080（装了tf1.14-gpu）上进行3DMM的提取。近期有计划将Deep3DRecon从TF转向Pytorch版本的，以适配RTX30+的显卡

**Comment by jackiezhang11** [comment]
好的，我换个1060显卡进行3DMM提取
