### ISSUE TITLE
"Extract_3dmm.py" in 3090 environment is not working

### ISSUE THREAD

**Issue by merif** [yerfor/GeneFace#52]
I followed the procedure below(process_target_person_video.md -> step2, CUDA_VISIBLE_DEVICES=0 python data_gen/nerf/extract_3dmm.py --video_id=$VIDEO_ID) , 

![1](https://user-images.githubusercontent.com/59863410/224278168-b8abe0c6-580a-4e48-a4dc-2b94efd7cba6.png)

and the above error occurred.

My conda environment configuration is here.
cudatoolkit               11.3.1               h2bc3f7f_2
cudnn                     8.2.1                cuda11.3_0
tensorflow                1.14.0          mkl_py37h45c423b_0  
pytorch                   1.11.0          py3.7_cuda11.3_cudnn8.2.0_0 
torchaudio                0.11.0+cu113             pypi_0    pypi
torchvision               0.12.0+cu113             pypi_0    pypi
pytorch3d                 0.6.2           py37_cu113_pyt1110

When using tensorflow, it seems that only cpu is recognized and gpu is not recognized.

**Comment by yerfor** [comment]
Hi, currently we use TF-based 3DMM extractor, which only supports RTX2080 and older GPUs. I'm planning to turn to a pytorch-based 3DMM extractor, which could work at RTX3090 and newer GPUs. 

I'm almost work it out. But it take times to validate the performance of the 3DMM coeff extracted by the new extractor. Apologize for the delay.

**Comment by zhangziliang04** [comment]
目前看版版本确实是个问题，linux环境下，才可以。windows环境不支持模型训练。deepface这个pytorch的版本，输出的文件结构不一致和tensor的版本不一致。转换的话，还是比较麻烦。

**Comment by yerfor** [comment]
你好，在最新发布的GeneFace v1.1.0 中，我们转向了pytorch版本的deep_3drecon，目前已经支持3090或者更新的显卡。所以我会关闭这个issue。
