### ISSUE TITLE
TF_LoadLibrary   undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by Hengameh400** [yerfor/GeneFace#54]
I could run all the cmds within [lrs3.md](https://github.com/yerfor/GeneFace/blob/main/docs/prepare_env/install_guide_lrs3.md) successfully, however, I got the following error when deep_3drecon is imported; do you have any suggestion for me? /thanks

>>> tf.load_op_library('kernels/rasterize_triangles_kernel.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "process_lrs3/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: GeneFace/deep_3drecon/mesh_renderer/bazel-bin/kernels/rasterize_triangles_kernel.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by yerfor** [comment]
Hi, since the currently used TF-based `deep3d_recon` is slow and hard to install, I have turned to a pytorch-based one. I'm almost working it out, but I still need some time to validate the performance. Ideally, I will update the code in several days.

**Comment by yerfor** [comment]
Hi, in the released GeneFace v1.1.0 code, we turn to pytorch-based `deep_3drecon`, in which you don't need to install the mesh_render. Therefore I will close this issue.
