### ISSUE TITLE
how to set files under checkpoints/${Video_ID}/audio2pose? where to download them?

### ISSUE THREAD

**Issue by Hengameh400** [yerfor/GeneFace#55]
https://github.com/yerfor/GeneFace/blob/main/scripts/infer_audio2pose.sh

could you plz guide where to find yml and model files related to audio2pose? 
did  you mention how to set files under checkpoints/${Video_ID}/audio2pose

Thanks.

**Comment by yerfor** [comment]
Hi, `audio2pose` is a beta module that has not been fully verified. You can ignore it and the code will use the GT pose.

**Comment by Hengameh400** [comment]
Thanks for your reply. Are you using GT pose only or you meant you are using GT KPs as well?

**Comment by yerfor** [comment]
Hi, only GT pose is used (which is a common practice by many NeRF-based methods), and KPs are generated by the postnet.
