### ISSUE TITLE
Links to files in release are broken

### ISSUE THREAD

**Issue by anthnyprschka** [yerfor/GeneFace#56]
Hi, I've tried downloading the files in the release (https://github.com/yerfor/GeneFace/releases/tag/v1.0.0), but the links for lrs3 dataset and May.mp4 seem to be broken.

**Comment by yerfor** [comment]
Hi, this link will be available in several days, along with a new version of 3DMM extractor.

Actually, I'm trying to turn to a PyTorch-based 3DMM extractor and uploading a new LRS3.zip based on this extractor. Since the google drive capacity is limited, I have to empty the space temporarily.

**Comment by yerfor** [comment]
About two days.

**Comment by yerfor** [comment]
Hi, the new codebase and dataset files are available. Therefore I will close this issue.
