### ISSUE TITLE
plotted posenet_infer outputs does not look like 68 facial landmarks

### ISSUE THREAD

**Issue by Hengameh400** [yerfor/GeneFace#58]
Hello, 

I run infer_posenet.sh; when I plot outputs of the model, e.g. 

at >>> https://github.com/yerfor/GeneFace/blob/main/tasks/postnet/lm3d_postnet_adv_sync.py#L122

            from matplotlib import pylab as plt
            i=16
            a = torch.reshape(refine_pred_lm3d.cpu().squeeze(), (-1, 3, 68))
            plt.scatter(a[i, 1, :], a[i, 2, :])
            plt.show()

            a = torch.reshape(refine_pred_lm3d.cpu().squeeze(), (-1, 68, 3))
            plt.scatter(a[i, :, 1], a[i, :, 2])
            plt.show()

none of are like facial KPs. They are like the attached file. Could you plz let me know if something is wrong with my reshaping? 

Thanks.

<img width="366" alt="Screenshot 2023-03-15 at 9 57 58 AM" src="https://user-images.githubusercontent.com/43616693/225384216-f1342470-23e6-45d4-9749-18cf655c670d.png">

**Comment by yerfor** [comment]
Hi, the pred_lm3d is `(lm3d - mean_shape) * 10`. You can refer to`reconstruct_idexp_lm3d(self, id_coeff, exp_coeff)` from `data_util/face3d_helper.py` for more details.

 If you want to visualize the landmark, please use `utils/visualization/lm_visualizer.py`

**Comment by Hengameh400** [comment]
Thanks. It works.
<img width="299" alt="Screenshot 2023-03-15 at 11 33 37 AM" src="https://user-images.githubusercontent.com/43616693/225408754-72fd9ed4-2ed6-4552-9f8d-997a707fe375.png">
