### ISSUE TITLE
Face Tracker batch_size

### ISSUE THREAD

**Issue by Gpwner** [yerfor/GeneFace#63]
我看到你的代码中face tracker的batch size=50
https://github.com/yerfor/GeneFace/blob/main/data_util/face_tracking/face_tracker.py#L219
但是RAD-NeRF中是64
https://github.com/ashawkey/RAD-NeRF/blob/main/data_utils/face_tracking/face_tracker.py#L180

请问这个batch size的大小有什么考究吗？有没有试过最大限度地调大这个值，会影响下游效果吗？感谢。

**Comment by yerfor** [comment]
影响不大，我用的是adnerf的设定，radnerf增大可能是为了加速数据处理流程。这个本质上都是过拟合数据的流程。实际上我觉得batch size小一点可能拟合的效果更好，即预测的head pose更准。如果你感兴趣的话可以比较一下bs=1和bs=59，最后算出来的best loss，应该是bs=1的更好
