### ISSUE TITLE
postnet training, disc_pos_conf, disc_true_loss = nan

### ISSUE THREAD

**Issue by bobo-wmdigit** [yerfor/GeneFace#65]
训练postnet时，disc_pos_conf, disc_true_loss都是nan，
定位到在geneface/tasks/postnet/lm3d_postnet_adv_sync.py文件中，
person_idexp_normalized = sample['person_ds']['idexp_lm3d'] 
获取的person_idexp_normalized数值全部都是0，导致
p = self.disc_model(x=person_idexp_normalized)
推理后，出来的tensor维度变成了[0, 1]；

请问导致sample['person_ds']['idexp_lm3d'] 中的数据全是0的可能原因会是什么呢？

**Comment by yerfor** [comment]
你好，请问你使用的是自己的视频吗，还是使用项目提供的May.mp4也出现了这个问题。

建议你可以在`process_data.sh`的最后一步，即运行`data_gen/nerf/binarizer.py`的第97行-105行的地方debug一下，看看是不是提取的3DMM coefficient文件（`video_coeff.npy`)里面的数据就有问题了。

如果是的话，你可以关注一下`python data_gen/nerf/extract_3dmm.py --video_id=$VIDEO_ID`这一步，看看问题出在哪里。

**Comment by bobo-wmdigit** [comment]
我用may裁剪出来的20秒视频，以及用了may.mp4，都是一样的情况，而且还会出现数据处理后报错的情况。

**Comment by yerfor** [comment]
感觉你可以debug一下看看是不是环境安装出错了，或许问题出在deep_3drecon提取3DMM的部分。

**Comment by bobo-wmdigit** [comment]
好的，非常感谢，这个环境。。。装了好久好久，我继续跟踪下你说的这部分吧

**Comment by yerfor** [comment]
好的，我在docs/prepare_env 文件夹提供了conda环境的yaml文件，你可以参考一下

**Comment by bobo-wmdigit** [comment]
嗯，另外请教下，我翻了几乎所有的yaml文件，没看到哪里有batch size的设定，用默认参数，postnet的两个loss一直不能下降到几乎都是0.5，感谢周末的支持

**Comment by yerfor** [comment]
你好，之前idexp_lm3d都为0的问题解决了吗，是什么原因呢？训练postnet的话，主要看的是`train/adv`是否能收敛在0.25～0.3左右，若能收敛则说明成功了。

batch的设计可以看一下`tasks/postnet/dataset_utils.py`，可以看到我们默认是把整个person_ds作为一个batch拿去训练的，同时也用到了audio2motion的batch，audio2motion的batch_size你可以看一下`tasks/audio2motion/dataset_utils/lrs3_dataset.py`的`batch_by_size`函数，经验上讲仅需50多个batch就可以遍历完一次lrs3数据集。

**Comment by bobo-wmdigit** [comment]
都为0的解决了，应该是权重有损坏，重新下载了权重之后解决了，
但是，现在看来adv还是不行，我把lr0跟lr1都改的很小，依然数据波动非常剧烈。跑了15000的steps了。我删除了所有权重，重设了超参，重新开始训练了。

**Comment by bobo-wmdigit** [comment]
训练nerf网络后进行推理得到如下报错：
![1021781679291233_ pic](https://user-images.githubusercontent.com/80187914/226264980-47532faa-55ec-4243-b1ce-5dad681d057a.jpg)
定位到lm3d_nerf_infer.py中的136~138行中的idexp_lm3d_normalized的shape维度是[272, 204]，但代码中似乎在试图使用3个维度的索引访问它。

额外加入：
idexp_lm3d_normalized = idexp_lm3d_normalized.reshape([-1,68,3])
能修复。

请问这个是源代码的错误吗，还是我的问题？

**Comment by yerfor** [comment]
你好，感谢指出，之前上传的lm3d_nerf_infer.py 文件在预处理lm3d阶段有错误，目前已经修复，你可以pull最新的代码来解决这个问题。

顺便，目前推荐使用RAD-NeRF来做渲染，你可以尝试运行`scripts/infer_lm3d_radnerf.sh`。相比原始的lm3d_nerf, lm3d_radnerf可以实现实时渲染和相似的渲染画质。

**Comment by bobo-wmdigit** [comment]
好的，那不是意味着。。。我还要重新训练一次。。。

**Comment by yerfor** [comment]
对。

如果你想快速验证生成的idexp_lm3d的质量的话，推荐你使用`utils/visualization/lm_visualizer.py`来生成`npy`文件对应的landamark的视频。

**Comment by bobo-wmdigit** [comment]
哎，我这边都跑好了，分别训练了postnet，lm3d_radnerf跟lm3d radnerf torso，但是结果跟demo比起来，差距太大，我用的may视频，自己输入的wav声音，有什么改良的建议吗？

**Comment by yerfor** [comment]
你可能需要提供更多细节，比如训练曲线等
