### ISSUE TITLE
training other target person

### ISSUE THREAD

**Issue by skunkwerk** [yerfor/GeneFace#66]
Hi, thank you for the great work.

I'm trying to train a model on Obama (or Macron), but the "/egs/datasets/videos/Obama2" folder contains only 13 YAML files, whereas the "May" folder contains 16 YAML files.  Do I need to create all 16 for Obama, or will training work with the 13 existing ones?

Are there any more pre-trained models for Obama/Macron that you could also share (as May's speaking style is very different from the others)?

thanks!

**Comment by yerfor** [comment]
Hi, you can directly copy the /egs/datasets/videos/May and rename it to  /egs/datasets/videos/Obama2, then in each yaml file, you should change the `video_id` from May to Obama2.

We only provide May's pretrained model, and you could train Obama/Macron in a similar way (you need to train a postnet, a lm3d_radnerf, and a lm3d_radnerf_torso model).
