### ISSUE TITLE
about head pose generation

### ISSUE THREAD

**Issue by flyingshan** [yerfor/GeneFace#67]
Great work!
I read about your paper, where you described that extracting head pose using the method from the paper"Accurate 3d face
reconstruction with weakly-supervised learning: From single image to image set". 
But by reading the code, I found that the head pose is extracted by ’data_util/face_tracking/face_tracker.py‘. I wonder if this observation is correct or not. Looking forward to your reply!

**Comment by kendo6666** [comment]
@yerfor 能简单介绍一下face_tracker完整流程吗？我看它最终主要就是为了输出NeRF所需的相机内外参。但是对于它的完整流程不太理解。

**Comment by yerfor** [comment]
@kendo6666 简单来说就是我们有3DMM提供的expression base、identity base等基mesh，对视频的每一帧，我们希望学习一个coeff（包含了expression、identity、euler_angle、translation），这个coeff定义了如何组合这些基mesh来重构出一个mesh。接下来就是优化这个coeff，我们希望重构的coeff与GT数据接近（体现在landmark error、rgb error等）。通过这个最优化过程，我们可以最优的coeff，而head pose（包括euler_angle、translation）就是coeff的一个分量。
