### ISSUE TITLE
When binarize the dataset, raise hparam KeyError: 'cond_win_size'

### ISSUE THREAD

**Issue by zhanchao019** [yerfor/GeneFace#7]
When I run the script `python data_gen/nerf/binarizer.py --config=egs/datasets/videos/May/adnerf.yaml`, it raises error:
`Traceback (most recent call last):
  File "data_gen/nerf/binarizer.py", line 22, in <module>
    exp_cond_win_size = hparams['cond_win_size']
KeyError: 'cond_win_size'`

**Comment by yerfor** [comment]
Please see [this reply](https://github.com/yerfor/GeneFace/issues/4#issuecomment-1422934254).
