### ISSUE TITLE
No such file or directory: 'data/binary/videos/Myvideo/trainval_dataset.npy

### ISSUE THREAD

**Issue by Hengameh400** [yerfor/GeneFace#72]
I run all the steps here: process_target_person_video.md over my video.

when I run: CUDA_VISIBLE_DEVICES=0 python tasks/run.py --config=egs/datasets/videos/May/lm3d_postnet_sync.yaml --exp_name=checkpoints/Myvideo/postnet

the code looks for this file: data/binary/videos/Myvideo/trainval_dataset.npy

could you plz guide how to generate data/binary/videos/Myvideo/trainval_dataset.npy?

Many thanks!

**Comment by Hengameh400** [comment]
note that I know for May, you have already prepred it here: https://drive.google.com/drive/folders/1QmXCLjVw4D1wMnrXIuH3ATnCYivSNxoB

how about for my video? thx

**Comment by Hengameh400** [comment]
it seems that this line of code was failed: python data_gen/nerf/extract_hubert_mel_f0.py --video_id=$1

at extract_mel_from_fname function [at [L47](https://github.com/yerfor/GeneFace/blob/main/data_gen/process_lrs3/process_audio_mel_f0.py#L47) ]: 

mel_basis = librosa.filters.mel(sample_rate, fft_size, num_mels, fmin, fmax)
Traceback (most recent call last):
  File "/home/ubuntu/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
TypeError: mel() takes 0 positional arguments but 5 were given


where I had these:
sample_rate
16000
fft_size
512
num_mels
80
fmin
80
fmax
7600

**Comment by Hengameh400** [comment]
it seems that it works by this >>
    mel_basis = librosa.filters.mel(sr=sample_rate, n_mels= num_mels, n_fft=fft_size, fmin=fmin, fmax=fmax)

**Comment by Hengameh400** [comment]
the above fixed the problem

**Comment by yerfor** [comment]
thanks, It seems to be a compatibility problem between different versions of librosa. I will update this in the code.
