### ISSUE TITLE
where to find data/binary/lrs3/stats.npy?

### ISSUE THREAD

**Issue by Hengameh400** [yerfor/GeneFace#75]
I used binary data 

lrs3.zip_part_aa  lrs3.zip_part_ab

    step1. Integrate the segments cat lrs3.zip.part_* > lrs3.zip .
    step2. Unzip processed_lrs3.zip and place it into the data/binary/lrs3 folder.
    step3. Move to Step4. Verification to verify installation.

and these are the files I have in lrs3 folder: 
sizes_train.npy  sizes_val.npy  spk_id2spk_idx.npy  train.data  val.data

could you plz guide where to find binary/lrs3/stats.npy, which is used by visualizer? 

thanks.

**Comment by Hengameh400** [comment]
could run the code by commenting load(stats)

**Comment by yerfor** [comment]
Hi, thanks for pointing out! `load(stats)` is a history code and we have commented it in the lastest commit.

**Comment by pyh007** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/May/aud_esperanto.npy'这个在哪里能找到啊

**Comment by yerfor** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/May/aud_esperanto.npy'这个在哪里能找到啊

这个文件应该是在执行process_data.sh的时候自动生成的，请看该文件的第六行：`python data_util/process.py --video_id=$1 --task=2`。你遇到的问题是这个文件未被正常生成。比较常见的情况是提取esperanto所依赖的wav2vec模型没有被成功地从huggingface上下载。你可以多尝试几次`python data_util/process.py --video_id=$1 --task=2`，看看能不能下载成功。实在不行可以挂个梯子。
