### ISSUE TITLE
新的说话人视频训练产生的mp4嘴不动

### ISSUE THREAD

**Issue by FrankWang2001** [yerfor/GeneFace#77]
您好，我在新引入了自己的一个超过3分钟的mp4视频后，按照您docs中的方式进行了训练，所有步骤都完成了。然后发现生成的视频中背景躯干头部的动作都是正常的，但是嘴部是没有动的，您方便帮我定位下是哪个模块的问题吗，如何解决呢，谢谢。

**Comment by yerfor** [comment]
你好，推荐你用utils.visualization/lm_visualizer.py检查一下postnet预测的lm3d是否正确

**Comment by FrankWang2001** [comment]
感谢您的回复
我马上试一下，谢谢

**Comment by FrankWang2001** [comment]
您好，我使用utils.visualization/lm_visualizer.py 在 infer_out/{video_id}/visualized_lm3d 目录下生成的视频文件中点是正常的，请问这是否意味着我在按照docs中的指导文件所训练的模型都是正常的，或者说是一部分模型正常。
另外，我在egs/datasets/videos/{video_id} 目录下新建的yaml描述文件都是从May文件下的yaml文件修改过来的（仅做了目录替换），请问这样是否会导致我训练的模型出现异常。
辛苦您再给我一些指引，万分感谢。

**Comment by yerfor** [comment]
你好，如果lm3d可视化结果是正常的话，问题可能出在lm3d_radnerf这个模型，你可以看看这个模型的checkpoint文件夹中的tensorboard日志，看看loss是否正常下降等。
关于第二个问题，yaml文件一般只需要修改目录，不过请注意修改了video_id和其他person-specific的信息。

**Comment by FrankWang2001** [comment]
好的，谢谢您的回复，我会继续尝试修改。

**Comment by FrankWang2001** [comment]
您好，我已经重新训练了lm3d_radnerf模型，已经训练了400000steps，loss都已经正常下降，但嘴型仍然不动，是否由于我训练视频的内容使用的是中文导致。请问您曾经使用过中文视频进行训练过吗。另外，对于修正嘴型不动这一问题，您还有其它建议吗。

**Comment by yerfor** [comment]
或许你可以看看`checkpoints/<your video>/lm3d_radnerf/validation_results/validation_250000/images`这个文件夹里生成的图片，看看预测生成的图像的嘴形是否和gt的图像一致

**Comment by FrankWang2001** [comment]
您好，感谢您的回复。
images下的png中，带有gt后缀的和不带有gt后缀的图像中的嘴形并不一致。

**Comment by yerfor** [comment]
那看起来是radnerf的训练有问题，或许你可以提供一下loss曲线以及psnr等指标

**Comment by FrankWang2001** [comment]
好的，我尝试一下，谢谢您的回复

**Comment by FrankWang2001** [comment]
您好，我经过了多次测试。现在我有一个猜想，请求您看一下：
我process后的gt img是不同的，但在lm3d_radnerf训练过程中，嘴型仍然不动。我猜想是我在process过程中所保存的gt lm3d是错误的，刚才在别的issue向您提问过关于gt lm3d的保存。
在整体使用process的sh中，我仅更改了data_util/extract_esperanto.py文件的`parser.add_argument('--fps', type=int, default=60)`，您原始代码audio FPS的default是50，但我传入了一个30帧的视频后，process失败，default=30后仍然失败，因此我改为60，process成功。
我想问您下是否因为我process中的参数不正确导致gt lm3d结果不正确，最后使得我lm3d_radnerf训练后的validation_results中的图片和gt图片不匹配，且嘴型均为单一嘴型，同时生成的视频也为单一嘴型。
另外，我如何可以验证我process生成的gt lm3d是正确的；还有，我该如何修改audio FPS。

**Comment by FrankWang2001** [comment]
请问您能否提供下，您在代码中提到过的其它训练使用的原视频，谢谢。

**Comment by yerfor** [comment]
有可能是因为fps的问题。我们目前只支持fps=25的512x512的视频，音频也只支持默认的setting。

关于其他的训练视频，你可以访问在README.md中提到的谷歌网盘链接。

**Comment by hskimi** [comment]
我这边也遇到的了类似的问题，研究了下，extract_image的部分是兼容不同fps的，提取的是25fps的image，但extract_3dmm的时候会采用原始视频的fps，导致3dmm与image不对应，因此训出了平均的、不太动的嘴型。
