### ISSUE TITLE
AssertionError: If capturable=False, state_steps should not be CUDA tensors.

### ISSUE THREAD

**Issue by Hengameh400** [yerfor/GeneFace#78]
to address the above error, [[here](https://github.com/yerfor/GeneFace/blob/main/tasks/radnerfs/radnerf.py#L75)],
I set capurable to True:

    if torch.cuda.is_available():
        self.optimizer.param_groups[0]['capturable'] = True

Do you think is that fine? /thanks

**Comment by yerfor** [comment]
Hi, I have not encountered with problem, have to tried directly setting CUDA_VISIBLE_DEVICES when running the code?

**Comment by Hengameh400** [comment]
I modify the code and whereever is needed, I set capturable to True. 

Now, I encounter other problems; e.g. when I train radnerf_torso, at some steps, torso_mse_loss starts to become nan. 

1step [01:14, 74.04s/step, image_psnr=20.2, lr_0=0.0005, torso_mse_loss=0.00956, torso_weights_entropy_loss=0.00559]
2step [01:55, 55.15s/step, image_psnr=20.6, lr_0=0.0005, torso_mse_loss=0.00866, torso_weights_entropy_loss=0.00379]
3step [01:59, 31.69s/step, image_psnr=nan, lr_0=0.0005, torso_mse_loss=nan, torso_weights_entropy_loss=nan]

I can see this line of code [[here](https://github.com/yerfor/GeneFace/blob/main/utils/commons/trainer.py#L335)], which I can modify to loss.isnan() to be recognized as True. I am wondering does that make sense to you or I should not do it.

    loss
    tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)

    loss is None
    False

**Comment by yerfor** [comment]
It is strange, maybe setting capturable to true is not the correct way. I have not encountered with this error following the steps in docs. What’s your difference with the provided guidance steps? Or maybe you could reinstall a new env following the command lines in the installation guide

**Comment by Hengameh400** [comment]
actually, I think, based on what I see  [[here](https://github.com/yerfor/GeneFace/blob/main/utils/commons/trainer.py#L335) , in your code, you are expecting to have None loss; 
but, instead of checking with 
      if loss is None >> I might need to check it with >> if loss.isnan()
when I apply that change [[here](https://github.com/yerfor/GeneFace/blob/main/utils/commons/trainer.py#L335), i.e.:
     if loss is None or loss.isnan():
         ...

in the beginning, the code is running well. but, at some point, I can see total_loss [here](https://github.com/yerfor/GeneFace/blob/main/tasks/radnerfs/radnerf_torso.py#L138) is set to 0 since 

    (isinstance(v, torch.Tensor) and v.requires_grad ) is False 

in that case, I need to modify this part of the code [[here](https://github.com/yerfor/GeneFace/blob/main/utils/commons/trainer.py#L343)]: 

            if not isinstance(loss, float):
                if loss.requires_grad:
                    if self.amp:
                        self.amp_scalar.scale(loss).backward()
                    else:
                        loss.backward()

after applying the above change, I can see the training log going well.

**Comment by yerfor** [comment]
Hi, when the density field has nan, it should be something wrong within CUDA extensions (Grid, raymarching, etc), this is not expected since the ray marching startegy of RAD-NeRF is dependent on the density field. As a result, you may find the loss cannot drop normally.

**Comment by Hengameh400** [comment]
could you plz share some tensorboard visualization of lm3d_nerf_torso and lm3d_nerf? 

> it should be something wrong within CUDA extensions (Grid, raymarching, etc),

I will try to install cuda 11.3 on base env and rerun the code although I doubt if this is the problem since inside geneface env, the cuda version is 11.3. By any chance, if you have any other recommendation to fix things for CUDA extensions, I would really appreciate to share with me. thanks.

**Comment by yerfor** [comment]
> I will try to install cuda 11.3 on base env and rerun the code although I doubt if this is the problem since inside geneface env, the cuda version is 11.3. 

please note that install cuda 11.3 means that you need to install the CUDA-11.3 at (this link](https://developer.nvidia.com/cuda-toolkit)

**Comment by Hengameh400** [comment]
this is the proper version, right? 

https://developer.nvidia.com/cuda-11-3-1-download-archive

and I select this set of options. If you have any comment on the selection below, I will appreciate to let me know.
thanks.

<img width="1237" alt="Screenshot 2023-03-29 at 9 28 59 AM" src="https://user-images.githubusercontent.com/43616693/228606265-d80844a9-c3a4-42b5-ad7a-0c89b3fb6c78.png">

**Comment by Hengameh400** [comment]
I installed cuda 11.3 on base env. This time, I did not get the capturable error. 


The following  is the log file I have after running: 
       run.py --config=lm3d_radnerf.yaml --exp_name=May/lm3d_nerf

could you plz let me know if the log is reasonable? 
<img width="1301" alt="Screenshot 2023-03-29 at 10 18 56 PM" src="https://user-images.githubusercontent.com/43616693/228736829-fb48fe9c-5080-4d7d-8ca4-7bdbf54d3b14.png">

at step 2000, I got the following error; I am wondering if you have any suggestion to fix it? /thx

2000step [02:20, 14.26step/s, ambient_loss=0, head_psnr=12.7, lr_0=0.000491, max_density=1.01, mean_density=5.36e-5, min_density=-1, mse_loss=0.0543, occupancy_rate=5.34e-5, step_mean_count=0, weights_entropy_loss=0.000181]
Traceback (most recent call last):
  File "GeneFace/tasks/run.py", line 26, in <module>
    run_task()
  File "GeneFace/tasks/run.py", line 21, in run_task
    task_cls.start()
  File "GeneFace/utils/commons/base_task.py", line 253, in start
    trainer.fit(cls)
  File "GeneFace/utils/commons/trainer.py", line 122, in fit
    self.run_single_process(self.task)
  File "GeneFace/utils/commons/trainer.py", line 186, in run_single_process
    self.train()
  File "GeneFace/utils/commons/trainer.py", line 286, in train
    pbar_metrics, tb_metrics = self.run_training_batch(batch_idx, batch)
  File "GeneFace/utils/commons/trainer.py", line 333, in run_training_batch
    output = task_ref.training_step(*args)
  File "GeneFace/utils/commons/base_task.py", line 109, in training_step
    loss_ret = self._training_step(sample, batch_idx, optimizer_idx)
  File "GeneFace/tasks/radnerfs/radnerf.py", line 192, in _training_step
    self.model.update_extra_state()
  File "/home/ubuntu/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "GeneFace/modules/radnerfs/renderer.py", line 249, in update_extra_state
    valid_mask = (self.density_grid >= 0) & (tmp_grid >= 0)
RuntimeError: CUDA error: device-side assert triggered

**Comment by yerfor** [comment]
hi, have you re-run the `install_ext.sh`? Have you reset the changes in you local code?

**Comment by Hengameh400** [comment]
and this is my log file after running 
python run.py --config lm3d_radnerf_torso.yaml --exp_name=May/lm3d_nerf_torso8

could you plz also let me know if this log seems to be normal to you? 


it seems that this one does not give me *RuntimeError: CUDA error: device-side assert triggered* 

<img width="1448" alt="Screenshot 2023-03-29 at 10 44 01 PM" src="https://user-images.githubusercontent.com/43616693/228740685-8b8e46e3-cf1d-4c40-8d43-8eddd1440c30.png">

**Comment by Hengameh400** [comment]
yes, I did create an env from scratch following your instructions [here](https://github.com/yerfor/GeneFace/blob/main/docs/prepare_env/install_guide.md); and I did run *bash docs/prepare_env/install_ext.sh*

**Comment by yerfor** [comment]
> and this is my log file after running python run.py --config lm3d_radnerf_torso.yaml --exp_name=May/lm3d_nerf_torso8
> 
> could you plz also let me know if this log seems to be normal to you?
> 
> it seems that this one does not give me _RuntimeError: CUDA error: device-side assert triggered_
> 
> <img alt="Screenshot 2023-03-29 at 10 44 01 PM" width="1448" src="https://user-images.githubusercontent.com/43616693/228740685-8b8e46e3-cf1d-4c40-8d43-8eddd1440c30.png">

cool, this run seems to work normally.

**Comment by Hengameh400** [comment]
I have just noticed that I had forgotten to checkout one of the files; now that I did that, I did not get the *RuntimeError: CUDA error: device-side assert triggere* error.

tmr, I will share with you tensorboards of my tranings to check if things are all set and then will close my two issues.

I truly truly appreciate your kind answers and your patience so far!

**Comment by yerfor** [comment]
ok, you can check the validation_results in the work dir.

**Comment by Hengameh400** [comment]
could you plz provide visualization of your tensorboard for radnerf an radnerf_torso?

You had already provided tb-visualization of posenet [here](https://github.com/yerfor/GeneFace/blob/main/assets/tips_to_select_postnet_ckpt.png) by which I can verify correctness of my tensorboard. If you could you provide tbs of radnerf an radnerf_torso, that would be great! /thx

**Comment by yerfor** [comment]
Sure, I provide the tensorboard log of `May/lm3d_radnerf` below:

The training metrics: 
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/48365204/228785878-2a0d308b-ea7a-4553-9b0e-24afcb394c94.png">

The density field info:
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/48365204/228785988-14785d41-423e-4a41-90c9-5c90c3c5a09a.png">

And the rendered results at iteration 10000 and iteration 70000:
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/48365204/228786226-f16f7e22-7722-40eb-aaa8-668e6a0532b5.png">

**Comment by Hengameh400** [comment]
thanks  a lot for sharing it. That says obviously something is wrong in my end. 

- I made a fresh checkout from you GeneFace repo. 
- I removed my existing geneface env
- I followed instructions [here](https://github.com/yerfor/GeneFace/blob/main/docs/prepare_env/install_guide.md) to reinstall
- this time I got this error; did you make any change on any of those installation files? could you plz let me know version of your numpy and tensorflow?

```
ERROR: Cannot install -r docs/prepare_env/requirements.txt (line 7) and numpy==1.23.0 because these package  versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.23.0
    tensorflow 2.6.0 depends on numpy~=1.19.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by Hengameh400** [comment]
I will change this [line](https://github.com/yerfor/GeneFace/blob/main/docs/prepare_env/requirements.txt#L7) of code to 

tensorflow==2.11.0 # you can flexible it, this is gpu version 

based on what I see [here](https://github.com/yerfor/GeneFace/blob/main/docs/prepare_env/geneface_rtx3090.yaml#L159)

**Comment by Hengameh400** [comment]
note that I am running the code on Ubuntu; I am not sure can I use geneface_rtx2080.yaml or geneface_rtx3090 instead of requirements.txt?

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal 
```

**Comment by Hengameh400** [comment]
am I right that the following warning is ignorable?

```
>>> import deep_3drecon
/home/ubuntu/anaconda3/envs/geneface/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/ubuntu/anaconda3/envs/geneface/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warn(f"Failed to load image Python extension: {e}")
```

**Comment by yerfor** [comment]
> am I right that the following warning is ignorable?
> 
> ```
> >>> import deep_3drecon
> /home/ubuntu/anaconda3/envs/geneface/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/ubuntu/anaconda3/envs/geneface/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
>   warn(f"Failed to load image Python extension: {e}")
> ```

it's okay

**Comment by Hengameh400** [comment]
If I am not mistaken, it is doing something meaningful this time :') [fingers crossed]

<img width="910" alt="Screenshot 2023-03-30 at 4 56 06 PM" src="https://user-images.githubusercontent.com/43616693/228989855-69b9f6e7-98f0-41ef-8c03-d8db3e79422c.png">

**Comment by yerfor** [comment]
great, I am glad that finally you could run the code normally. I will find a better requirements in few days.
