### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered *** while training lm3d_radnerf

### ISSUE THREAD

**Issue by Hengameh400** [yerfor/GeneFace#79]
when I train > python run.py --config lm3d_radnerf.yaml --exp_name=May/lm3d_nerf

it went well in the beginning, but, suddenly it gives me this error:
       RuntimeError: CUDA error: device-side assert triggered

 the following is my log file; and it seems that when I rerun the code, it load the latest  best model and continue training till it hit the same error. I am wondering if it makes sense at all to you or what is happening in my end is something unexpected by you? /thanks.

| cond_prenet Trainable Parameters: 0.050M
| cond_att_net Trainable Parameters: 0.004M
| position_embedder Trainable Parameters: 1.807M
| ambient_net Trainable Parameters: 0.029M
| ambient_embedder Trainable Parameters: 1.111M
| sigma_net Trainable Parameters: 0.041M
| direction_embedder Trainable Parameters: 0.000M
| color_net Trainable Parameters: 0.019M
Sanity Val: 100%|███████████████████████████████| 2/2 [00:01<00:00,  1.53step/s]
| Validation results@6000: {'total_loss': 0.6406, 'mse_loss': 0.054, 'lpips_loss': 0.5866}
8000step [02:17, 19.21step/s, ambient_loss=256, head_psnr=5.43, lr_0=0.000464, max_density=0.42, mean_density=2.28e-5, min_density=-1, mse_loss=0.287, occupancy_rate=5.44e-5, step_mean_count=0, weights_entropy_loss=0.000181]
Valid:   0%|                                          | 0/100 [00:00<?, ?step/s]
Valid:   1%|▎                                 | 1/100 [00:00<00:19,  5.00step/s]
..
Valid:  53%|█████████████████▍               | 53/100 [00:10<00:09,  4.80step/s]
8000step [02:28, 19.21step/s, ambient_loss=256, head_psnr=5.43, lr_0=0.000464, max_density=0.42, mean_density=2.28e-5, min_density=-1, mse_loss=0.287, occupancy_rate=5.44e-5, step_mean_count=0, weights_entropy_loss=0.000181]
Valid:  55%|██████████████████▏              | 55/100 [00:11<00:09,  4.78step/s]
..
Valid: 100%|████████████████████████████████| 100/100 [00:20<00:00,  4.82step/s]
| Validation results@8000: {'total_loss': 0.6417, 'mse_loss': 0.0545, 'lpips_loss': 0.5872}
03/29 04:57:35 AM Epoch 00000@8000: saving model to checkpoints/May/lm3d_nerf/model_ckpt_steps_8000.ckpt
03/29 04:57:48 AM Delete ckpt: model_ckpt_steps_6000.ckpt
03/29 04:57:48 AM Epoch 00000@8000: val_loss reached 0.64170. Saving model to checkpoints/May/lm3d_nerf/model_ckpt_best.pt
/opt/conda/conda-bld/pytorch_1656352660876/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [1392,0,0], thread: [64,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1656352660876/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [1392,0,0], thread: [65,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1656352660876/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [1392,0,0], thread: [66,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1656352660876/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [1392,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1656352660876/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [1392,0,0], thread: [68,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1656352660876/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [1392,0,0], thread: [69,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1656352660876/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [1392,0,0], thread: [70,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1656352660876/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [1392,0,0], thread: [71,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

sigmas
PyDev console: starting.
Traceback (most recent call last):
  File "/home/ubuntu/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/_tensor.py", line 338, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/home/ubuntu/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/_tensor_str.py", line 481, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/home/ubuntu/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/_tensor_str.py", line 447, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/home/ubuntu/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/_tensor_str.py", line 270, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/ubuntu/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/_tensor_str.py", line 295, in get_summarized_data
    return torch.cat((self[:PRINT_OPTS.edgeitems], self[-PRINT_OPTS.edgeitems:]))
RuntimeError: CUDA error: device-side assert triggered
cas_xyzs
Traceback (most recent call last):
  File "/home/ubuntu/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/_tensor.py", line 338, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/home/ubuntu/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/_tensor_str.py", line 481, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/home/ubuntu/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/_tensor_str.py", line 447, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/home/ubuntu/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/_tensor_str.py", line 270, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/ubuntu/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/_tensor_str.py", line 302, in get_summarized_data
    return torch.stack([get_summarized_data(x) for x in (start + end)])
RuntimeError: CUDA error: device-side assert triggered

**Comment by yerfor** [comment]
Hi, it is strange that at iteration 8000 the mse loss is still nearly 0.05, which is much higher that expected. Maybe the CUDA-extensions are not worked correctly. I suppose you should check the installation of cuda extensions.
