### ISSUE TITLE
why training torso rely on head model?

### ISSUE THREAD

**Issue by Hengameh400** [yerfor/GeneFace#84]
could you plz let me know why training for torso rely on head_model? 
head_model needs to be loaded [here](https://github.com/yerfor/GeneFace/blob/main/tasks/radnerfs/radnerf_torso.py#L34)

I think if that folder is empty, still we can keep traning for torso. 

thx

**Comment by Hengameh400** [comment]
this is very minor. I will close it.

**Comment by yerfor** [comment]
Because during inference the torso model need to cooperate with head model to render the final image. So it is necessary for jointly training to achieve natural head-torso connection results
