### ISSUE TITLE
postnet和radnerf模型训练有先后顺序吗？

### ISSUE THREAD

**Issue by lwcode** [yerfor/GeneFace#85]
postnet和radnerf模型训练有先后顺序吗？egs文件夹里的radnerf模型的yaml似乎又不依赖于postnet，并且可以直接训练radnerf，那么postnet是做什么用？是我什么地方搞错了吗？我按照readme里的顺序训练了三个自己的视频，出现的问题都类似：嘴型幅度很小；radnerf里的gt和生成图片嘴型不是每张都能一致，并且加大训练次数（25万到60万次并不会明显收敛和变好）；用训练后的模型推理时部分图片是有色块像损坏一样。。。我是不是有什么地方弄错了？

**Comment by yerfor** [comment]
postnet 用于后处理audio2motion模型输出lm3d，所以训练完audio2motion模型后需要再训练一个postnet。

**Comment by lwcode** [comment]
> postnet 用于后处理audio2motion模型输出lm3d，所以训练完audio2motion模型后需要再训练一个postnet。
> 
> radnerf训练时使用gt lm3d，推理时使用postnet预测的lm3d
非常感谢你的回复，如果训练时验证的嘴型跟真值有部分匹配不上，可能是训练视频质量不好，或者是process_data.sh这个环节提取的数据存在问题，或者是radnerf需要像老版本一样多次初始化才行？比如下面的图（左边是推理结果，右边是gt）：
![image](https://user-images.githubusercontent.com/12107803/229403242-604dc7ff-06b5-43fb-8367-db812c989199.png)
还有生成的图像模糊，迭代60万次后还是这样：
![image](https://user-images.githubusercontent.com/12107803/229403351-1f978893-78f2-4960-a132-eb02130a4792.png)
这是第二个视频结果：
![image](https://user-images.githubusercontent.com/12107803/229403655-b5a52306-7d5c-4a30-b0d2-f495cabd1bab.png)

**Comment by FrankWang2001** [comment]
> postnet 用于后处理audio2motion模型输出lm3d，所以训练完audio2motion模型后需要再训练一个postnet。
> 
> radnerf训练时使用gt lm3d，推理时使用postnet预测的lm3d

您好，您所说的gt lm3d是保存在哪一个文件里，我在训练radnerf的过程中是如何将这个gt lm3d传给模型的？

**Comment by yerfor** [comment]
存在vid_coeff.npy中，在经过binarize之后会存在trainval_dataset.npy里。你可以搜索一下idexp_lm3d_normalized。在训练时，idexp_lm3d被用作nerf的condition来控制人脸的变形

**Comment by FrankWang2001** [comment]
> 

请问idexp_lm3d_normalized是在某个代码文件里的一个参数，还是在某个配置文件下的参数？

**Comment by yerfor** [comment]
是代码中的变量，它由3dmm coefficient变换而来。具体生成方法可以看一下data_util/face3d_helper.py这个文件

**Comment by Gpwner** [comment]
@yerfor 请问如何可视化gt训练radnerf时的gt 3d landmark？我尝试用lm_visualizer.py，但发现结果是错误的
![image](https://user-images.githubusercontent.com/19349207/230338956-6d97b26a-7279-45f4-bb2b-8cd007c9e743.png)

**Comment by anan-dad** [comment]
@lwcode did you solve the problem?

**Comment by anan-dad** [comment]
> postnet 用于后处理audio2motion模型输出lm3d，所以训练完audio2motion模型后需要再训练一个postnet。
> 
> radnerf训练时使用gt lm3d，推理时使用postnet预测的lm3d

@yerfor 请问这个gt lm3d的生成具体是在哪一个过程产生的？
