### ISSUE TITLE
checkpoint directory mismatch

### ISSUE THREAD

**Issue by JamesLong199** [yerfor/GeneFace#86]
Hi,

There is a minor issue regarding the checkpoint directory, which is a mismatch between the [model training instruction page](https://github.com/yerfor/GeneFace/blob/main/docs/train_models/train_models.md) and the actual file structure of the repo.

In the training instruction, the variable "exp_name" is set to "--exp_name=checkpoints/video_id/postnet" (and ".../lm3d_radnerf" etc.), while the checkpoint directory is actually set to "checkpoints/exp_name" in [the code](https://github.com/yerfor/GeneFace/blob/69c0967e6a19c605b876979f25bbdfbf4fa5bc10/utils/commons/hparams.py#L77) , which becomes "checkpoints/checkpoints/video_id/postnet". This would eventually cause errors in the following training and inference steps. 

Overall a great repo, great instruction and maintenance, looking forward to future upgrades :)

**Comment by yerfor** [comment]
Thanks for pointing out that, in the latest commit I have fixed the bugs in docs.
