### ISSUE TITLE
关于运行环境的问题

### ISSUE THREAD

**Issue by Kafeyun** [yerfor/GeneFace#87]
你好，请问这个项目支持windows环境运行吗？我尝试在win环境下运行，但是在运行pip install ./modules/radnerfs/encoders/freqencoder/时遇到了问题，看您提供的例子是基于Ubuntu的。

**Comment by yerfor** [comment]
我们没有尝试过在windows环境运行。freqencoder等cuda extension是lm3d_radnerf的依赖，你可以去RAD-NeRF仓库寻求帮助。或者你可以尝试一下训练不使用freqencoder的lm3d_nerf。

**Comment by Kafeyun** [comment]
谢谢解答

**Comment by Castrol68** [comment]
> 谢谢解答
请问您后面是如何解决的，我也遇到了这个问题，刚从事这方面额研究，求赐教

**Comment by azouever** [comment]
> > 谢谢解答
> > 请问您后面是如何解决的，我也遇到了这个问题，刚从事这方面额研究，求赐教

你好，问下您后续在windows上面是否部署成功了
