### ISSUE TITLE
当我使用1920*1080的视频作为raw提取特征时候出现警告

### ISSUE THREAD

**Issue by Chopin68** [yerfor/GeneFace#91]
并且我查看debug渲染的时候，发现并没有渲染在面部
![image](https://user-images.githubusercontent.com/75252160/230317946-7d0af1a9-e3b3-4cce-afe8-7a21c88ab909.png)

还一直显示这个警告
 To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete.

**Comment by yerfor** [comment]
你好，目前的代码只支持512x512的视频，你可以用pr截取一下。
