### ISSUE TITLE
smo_win_size参数的意义

### ISSUE THREAD

**Issue by Gpwner** [yerfor/GeneFace#93]
请问egs/egs_bases/radnerf/lm3d_radnerf.yaml文件中的smo_win_size: 5 的意思是将最近5帧的3D landmark作为当前帧的3Dlandmark吗？为了做平滑？感谢大佬

**Comment by yerfor** [comment]
是的，主要是为了利用AD-NeRF提出的AttNet进行平滑。

ad-nerf和rad-nerf也用了这个trick，只不过他们的smo_win_size是8。
