### ISSUE TITLE
Regarding Postnet training

### ISSUE THREAD

**Issue by lirus7** [yerfor/GeneFace#94]
Hey! 
Thanks for open-sourcing the code for GeneFace.

I get the following error while training Postnet for a person present in lrs3 (shaheen).

```
ERROR: Unexpected bus error encountered in worker. This might be caused by insutticient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
3.39s/step, adv=0.277, disc_fake_loss=0.232, disc_neg_conf=0.4
177. disc nos conf=0. 489. disc true loss=0. 263. 1r 0=9.000469. 1r 1=0.0001.
"/home/ubuntu/anaconda3/envs/gentace/11b/python3.9/site-packages/torch/utils/data/dataloader.py",line1134, in _try_get_data
aala = selT. aaca Qu
leue.gettimeout=Limeout
File "home ubuntuanaconda‹ envs gentaceb ovthons. 9 queuerv. ane 189. 1n det

```
Can you please help me on what are the kind of system requirements? I am currently using a machine with 24GB GPU RAM and 64 GB RAM with 16 cores.

**Comment by yerfor** [comment]
Hi， this is strange. It seems the data loader is waiting too long and got killed. Maybe you could set load_ds_to_memory=True in the config, with this setting we will accelerate the IO, and ideally can handle this problem.

**Comment by lirus7** [comment]
Okay. Let me try it.
