### ISSUE TITLE
如何使推理速度变快

### ISSUE THREAD

**Issue by FrankWang2001** [yerfor/GeneFace#95]
请问如何可以给推理速度加快。使用双卡是否可以加速，如果可以如何配置呢。谢谢

**Comment by yerfor** [comment]
我们的lm3d_radnerf目前的推理速度在10fps左右，相比原始radnerf的25fps有所下降，这是因为我们（1）增大了hid_size（64=>128）以提升性能，这增加了100%的计算量；（2）增大了视频的分辨率（450x450=>512x512），增加了30%的计算量。

理论上可以使用多卡进行加速，你只需要在CUDA_VISIBLE_DEVICES时指定多个卡即可实现这个功能（参考`scripts/infer_lm3d_nerf.sh`文件的第3行）。

具体的代码实现可以见`inference/nerfs/base_nerf_infer.py`文件的`def _forward_nerf_task_ddp(self, gpu_idx, batches, hparams_)`这个函数。这个功能在lm3d_nerf_infer时进行了验证，但是我目前还没有验证过lm3d_radnerf的infer，如果你遇到bug的话，欢迎提出。
