### ISSUE TITLE
请教头部感知躯干

### ISSUE THREAD

**Issue by kendo6666** [yerfor/GeneFace#99]
看介绍中有提到“Moreover, we learn a NeRFbased renderer conditioned on the predicted motion. A head-aware torso-NeRF is proposed to eliminate the head-torso separation problem.”
想请问一下，如果只渲染头部，不渲染躯干，会有像AD-NeRF/RAD-NeRF那样头部和躯干分离(或者说头和躯干结合处明显有瑕疵)的问题吗？

**Comment by yerfor** [comment]
我理解的你的意思是使用gt的torso吗，这可能也会导致head torso separation，因为渲染的脑袋表情有变化，脑袋形状的变化导致下颚线并不和gt视频里一样。

**Comment by yerfor** [comment]
这方面我没有探索过，或许可以训练一个额外的GAN来impaint一下
